### ISSUE TITLE
Only show LTE for LTE enabled variants.

### ISSUE THREAD

**Issue by robputt** [NebraLtd/hm-diag#101]
LTE detected shows even for non-outdoor units. I'm wondering whether we should add a field to the [hardware variants](https://github.com/NebraLtd/helium-hardware-definitions) of "LTE Support" or something to that effect? So that we can automatically determine whether it should even bother to check for LTE? - https://github.com/NebraLtd/hm-diag/pull/92#issuecomment-898944681

**Comment by shawaj** [comment]
guess we will need to add celullar to tests as well https://github.com/NebraLtd/hm-diag/blob/master/hw_diag/tests/fixtures/diagnostic_results.py
