### ISSUE TITLE
Caching for Static Files

### ISSUE THREAD

**Issue by robputt** [NebraLtd/hm-diag#102]
Add caching headers for static files to prevent re-download each page refresh as requested by @shawaj here - https://github.com/NebraLtd/hm-diag/pull/92#issuecomment-898944681

**Comment by robputt** [comment]
I think this works once we switched to gunicorn as when testing I see 304s returned in the browser network developer tab (Content not changed). If not we are going to need to run nginx or something to inject caching headers which seems overkill for such a small utility.

**Comment by vpetersson** [comment]
Yeah it's not like there will be much load on this. Feels a bit over kill to do more than whatever we get for free from the WSGI server.
