### ISSUE TITLE
Sync percentage rounding

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#104]
The sync percentage should only have 2 decimals and should round up to 100%, if higher than 99.99% as customers might think it is not fully synced.

**Comment by KevinWassermann94** [comment]
And to expand this the sync percentage can go above 100 as seen in this picture:
![image](https://user-images.githubusercontent.com/82943687/129576786-67f30a65-37be-429a-b511-98f4816caee7.png)

**Comment by shawaj** [comment]
This relates to #71 as well

I was trying to get clarity from helium on what actually constitutes synced in https://github.com/helium/miner/issues/957 but haven't had an answer yet.

In the explorer they call within 1500 blocks synced now but that's just an approximation. As the diagnostics is more real time I think we can be more accurate with this but not sure
