### ISSUE TITLE
Rename Modem detected

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#105]
We should rename Modem detected to something like LTE Modem detected as it might cause confusion for indoor hotspot owners.

**Comment by shawaj** [comment]
@KevinWassermann94 I asked to change this away from LTE because it may not be LTE 

However, this isn't supposed to show for indoor Hotspots. See #101

**Comment by shawaj** [comment]
@KevinWassermann94 do you think "Modem Detected" is fine or maybe "Cellular Modem Detected" or perhaps just "Cellular Detected" ?
