### ISSUE TITLE
Potentially add periodic speedtest / wifi strength test?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#110]
Could be interesting to periodically do a speed test (or perhaps on-demand) on the connection as a way to debug crappy internet connections?

And could possibly add a wifi strength/quality check. 

Maybe overkill though I dunno...

**Comment by vpetersson** [comment]
Interesting idea. We could use something like "speed-test" or even run our own "iperf" tests.

**Comment by robputt** [comment]
Alot of the work for this is already done here - https://github.com/robputt/ConnTestD, mostly a copy and paste job 😂
