### ISSUE TITLE
Still using nginx?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#120]
I thought we were no longer using nginx so guessing this file is no longer needed?

https://github.com/NebraLtd/hm-diag/blob/master/default.conf

Along with installing nginx in the dockerfile:
https://github.com/NebraLtd/hm-diag/blob/7eb643a34835b96b0ae4ec358fbce082bdcd9d32/Dockerfile#L11

**Comment by vpetersson** [comment]
Correct. That can all be cleaned up.
