### ISSUE TITLE
Sync Time Estimator

### ISSUE THREAD

**Issue by jsonpoindexter** [NebraLtd/hm-diag#127]
Hello all!

I created a little nodejs script that uses the info from the diagnostics endpoint to calculate an estimated sync time duration that periodically updates. https://github.com/jsonpoindexter/nebra-helium-sync-estimate

I was in the process of migrating it over to a web app but have been stopped by CORS.

I was wondering if it would be possible to enabled CORS server side, or would you all be partial to me opening up a PR to add an 'Estimated Sync Time' field to the diagnostics dashboard?

**Comment by shawaj** [comment]
@robputt FYI

**Comment by vpetersson** [comment]
Interesting idea, @jsonpoindexter. I think we'd probably have to rewrite this to Python to run it inside the diagnostics page.

**Comment by shawaj** [comment]
No longer sync to chain so closing this
