### ISSUE TITLE
Diagnostics page unstable

### ISSUE THREAD

**Issue by Funkton** [NebraLtd/hm-diag#134]
Since the last few updates the diagnostics page keeps crashing and fails to connect. Sometimes it takes 5 minutes, sometimes 30, other times it fails to start completely.
8.24.4 update finally got synced up and started witnessing, then the 8.25 update came and it hasn't been good ever since.
The real troubles started with the 8.21 update. 8.16 was stable and functioning fine, ever since then it's been unstable and non-functional.

![Screen Shot 2021-08-26 at 11 20 59 AM](https://user-images.githubusercontent.com/5308216/131015763-01083332-b0f7-4295-97e4-bd17e278b819.png)

**Comment by shawaj** [comment]
Closing this as haven't heard anything more in ages
