### ISSUE TITLE
Re-instate Sentry

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#139]
**User Story**
As a Nebra employee, I want to receive warnings on critical errors so that I can take action.

**Notes**
Looks like we lost Sentry at some point. We need to reinstate it.

Viktor's research: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1640262898204200

**Acceptance Criteria**
- Enabled on all repos
- Analysis of current errors
- Tune errors so that only critical ones are triggering
- Ensure best practices defined for receiving Sentry warnings (email notifications, Slack integration)

**Comment by shawaj** [comment]
This is due to #53 filling up sentry IIRC

**Comment by vpetersson** [comment]
No i think we lost it in @robputt's rewrite.

**Comment by shawaj** [comment]
Was originally removed here - https://github.com/NebraLtd/hm-diag/commit/5f0c9e2d54bfbba82b73c93a709909fe0b892876

But then I guess because it was commented out it wasnt pulled accross

**Comment by marvinmarnold** [comment]
@ilyastrodubtsev I created two new Sentry projects for hm-upnp and hm-block-tracker.
