### ISSUE TITLE
Port 80 not responding.

### ISSUE THREAD

**Issue by gurpalw** [NebraLtd/hm-diag#144]
My miner has been running fine for over a month (with port 44158 forwarded)until the 5th September when the miner reported a relayed status.

I rebooted the miner, connected to port 80, and could see that it was no longer in relay. However, soon after this, the miner went offline. I attempted another reboot and could ping the miner consistently, and Bluetooth diagnostics came back OK. however, i now cannot access the IP diagnostics page and telnet reports port 80 as closed.

``` 
  telnet 192.168.1.217 80                                                                                                                                                           
Trying 192.168.1.217...
telnet: connect to address 192.168.1.217: Connection refused
telnet: Unable to connect to remote host
```

I have tried multiple reboots to no avail.

i logged a ticket(#273208) with sales@nebra.com, but the responses have been unhelpful to say the least. The support guy keeps telling me to try connecting to 192.168.1.111 instead of .217 which is the ip address my miner has. I even proved this by showing the latest bluetooth diag which i have attached below as well. He also asked me to reboot, even though i had already said i had tried this multiple times.

please help.

Latest Bluetooth diagnostic:
```
Hotspot: bouncy-alabaster-jay
Hotspot Maker: Nebra Ltd
Address: 11H6D1cV1R3HWt4xE1yMfw3h3y89WzeGJgzHhhBwQ4w4pSaSLr2
Connected to Blockchain: yes
Dialable: yes
Height: 1,002,109
Last Challenge: 2021-09-08 10:02 AM
Firmware: 2021.09.03.0
App Version: 3.4.7
Wi-Fi MAC: 8C:88:1B:70:04:5C
Eth MAC: 00:BD:27:EF:7E:DF
NAT Type: None
IP Address: 192.168.1.217
Disk status:
Report Generated: 2021-09-08 12:12 PM
Device Info: iPhone13,4 | ios 14.6
```

**Comment by shawaj** [comment]
you seem to be connected via both wifi and ethernet which is why you are getting two IP addresses - 192.168.1.217 and 192.168.1.111

If you check on https://dashboard.nebra.com you will see that both of these IP addresses are assigned to your device.

anyway, we will follow up via support ticket.
