### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#152]
**Acceptance criteria**
- Tests run as part of Github workflow
- Most likely will need to happen in hm-pyhelper

**Comment by shawaj** [comment]
@marvinmarnold both diag and hm-pyhelper have got unit tests now so guess we can close this one?

**Comment by marvinmarnold** [comment]
Our coverage probably isn't where it should be, but I'm fine closing this.
