### ISSUE TITLE
Can you please get CPU and Temperature stats into the diag JSON

### ISSUE THREAD

**Issue by nhatfield** [NebraLtd/hm-diag#157]
I created a monitoring platform for endusers to watch their miners. Supporting as many vendors as possible that have useable info in their diag. You can check that project here: https://github.com/nhatfield/hnt_monitor/tree/4.2.0

It would be awesome to see this from nebra:

* cpu usage
* cpu temperature
* memory usage
* storage usage

Thanks

**Comment by shawaj** [comment]
@nhatfield thanks for the suggestion. we are looking at adding a number of different things, however we will probably put this page behind authentication (password protected) at some point

we also have https://dashboard.nebra.com already

**Comment by vpetersson** [comment]
@nhatfield Pulling this from `hm-diag` wouldn't be very useful as you'd have to be at the same network (which rarely is the case for people with multiple miners). Also, as @shawaj mentioned, we already have this data in the Dashboard.

**Comment by nhatfield** [comment]
@shawaj that is no problem, when you move it to an authenticated we can still support it :) It is just a `curl` command that is pulling the json down. I will just have to make some code updates to support the authentication header and method you guys choose. With all that said though, does that mean that the new password protected version is when you will release those other metrics? 

@vpetersson that's true but this is small enough to run on a rapberry pi. So essentially you just need enough space to fit 2 small items in one location (the PI and the miner). The collector is all that is needed, and it runs on a docker container. This allows the collection to be done from the same network as the miner. The other option is to open the firewall rule for a non standard port like 8080 => 80 on the miner from source ip (your main monitor location ip) and do your collection that way. There's a lot of easy options to solve the remote miner use case.

Thanks

**Comment by nhatfield** [comment]
@shawaj  @vpetersson as the platform grows, many more users are looking for this type of diag. It would be great to get these out so we can start monitoring cross vendor comparisons. So far, because of this limitation we recommend other brands that offer these diag metrics instead of Nebra. It would be nice to add you to the top of the list of recommended hotspots like bobcat, sensecap, and syncrobit already are. Seems like a super easy win for such a small amount of tech debt...especially in a world where the most profitable and effective miners will be the ones off grid, needing to monitor these stats in a unified way! Imagine getting an IOT device that can only been seen in helium console... would you buy it? Or would you rather buy the IoT device that can be seen in any console... datacake? local ui? .... This is the same for hotspots

Thanks,

**Comment by shawaj** [comment]
You can already do this from our dashboard 👍
