### ISSUE TITLE
Allow to reboot the miner from the local network. 

### ISSUE THREAD

**Issue by wolasss** [NebraLtd/hm-diag#172]
The ability to reboot the miner from local website is crucial. Consider this example:

1. My miner stopped working for some unknown reason. 

2. I have a VPN access to the local miner's network and I see this:

<img width="1580" alt="Screenshot 2021-10-19 at 22 06 43" src="https://user-images.githubusercontent.com/1525324/137983023-882a7f21-288f-4e8b-b8cd-6958015db082.png">

3. Ok, I go to the Nebra dashboard to reboot the hotspot and I see this:

<img width="2285" alt="Screenshot 2021-10-19 at 22 06 51" src="https://user-images.githubusercontent.com/1525324/137983103-e1292bc4-384f-47a2-8e1b-d2f6671b4dd3.png">

4. I am stuck with a not-working hotspot in a remote location that I have restricted access. Great. 

Nebra dashboard is not reliable at all, rebooting a hotspot from a locally served diagnostics page should be a basic feature....

**Comment by wolasss** [comment]
I see where you are coming from, but adding a Basic HTTP authentication is a 30 min task (very simple in almost all scenarios), that is not a particularly good excuse... 

I opened this issue to give you guys constructive feedback because right now I am very disappointed so far with the nebra devices, I do not plan to buy another Nebra and I will not recommend them to any of my friends right now. Why? Because my overall user experience so far is bad. I have hotspots from 3 different manufacturers and so far, the nebras are causing the most problems. What problems? 

> Or go to the location to power cycle it. 

Well such as this one. This particular hotspot is in a remote area and I have restricted access so Nebra just caused me some trouble. This is not the smooth experience that it could have been.

I feel disappointed because Nebra never asked me for feedback, never asked me what features I would like to get and yet you state that for "The vast majority of users, the dashboard is sufficient". Did you actually ask your users or this is just an assumption? I know personally other people who have a similar experience with these devices. But you wouldn't know, would you? 

In my opinion, Nebra as a company needs to rethink the customer experience, cause right now **some** of your clients are nothing but frustrated.

**Comment by shawaj** [comment]
You don't need to go to the remote location. You just need to use the dashboard, as I've said several times already.
