### ISSUE TITLE
Remove scheduler

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#174]
With the new rework, combined with the fact that we are also checking the status of diagnostics before starting other services, we should probably rework the way we run the diagnostics to make it more snappy.

Here's what I suggest:

* We remove the scheduler all together for serving diagnostics (and instead add a cache on success perhaps)
* We leave the GSC upload in the scheduler

**Comment by vpetersson** [comment]
Initially, I thought it would be a good idea to remove the file cache entirely. However, after checking how long it takes to run this function, I changed my mind:

```
/srv # python -c 'from hw_diag.tasks import perform_hw_diagnostics
> 
> ^C
> python -c 'from hw_diag.tasks import perform_hw_diagnostics^C
> '
/bin/sh: python: not found
/srv # time python3 -c 'from hw_diag.tasks import perform_hw_diagnostics; perform_h
w_diagnostics()'
[...]
INFO:root:Diagnostics complete
real    0m 7.83s
user    0m 5.25s
sys     0m 0.83s
```

**Comment by shawaj** [comment]
We probably can simplify `perform_hw_diagnostics` ... For example the animal name, helium address, hardware serial, frequency, variant are never going to change so only need to be checked once at first run.

Region plan, firmware version are not going to change without the container restarting.

Sync percentage, height status, miner connected to blockchain, relayed are probably the ones that need updating most regularly

ECC detected, lora operational, LTE detected, Bluetooth detected, WiFi Mac address, Ethernet Mac address are unlikely to change very often so could be on a less frequent time period
