### ISSUE TITLE
improve miner diagnostics handling

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#185]
Currently we have the following:

https://github.com/NebraLtd/hm-diag/blob/262e7c76772a7d6269f70c151a8fcfab63dd852e/hw_diag/utilities/miner.py#L21-L25

This can be improved in a few ways:

- MC
- MD
- MR

**Comment by vpetersson** [comment]
@shawaj I'm closing this one out as we are in the midst of refactoring this a fair bit.
