### ISSUE TITLE
Ensure all exceptions thrown by miner are caught

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#204]
Related to: https://github.com/NebraLtd/hm-diag/issues/181
Exceptions created in this PR: https://github.com/NebraLtd/hm-pyhelper/pull/45

**Comment by vpetersson** [comment]
Acceptance criteria:

- [ ] Stop all services other than hm-diag on the miner
- [ ] Make sure both the diagnostics page and the `/json` payload is being served with all other services stopped

**Comment by marvinmarnold** [comment]
@SebastianMaj can you make sure [this invocation](https://github.com/NebraLtd/hm-diag/blob/master/hw_diag/tasks.py#L42) is also caught?

In testing, I am seeing:

```
 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
10.11.21 19:26:01 (-0600)  diagnostics      rv = self.handle_user_exception(e)
10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
10.11.21 19:26:01 (-0600)  diagnostics      rv = self.dispatch_request()
10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
10.11.21 19:26:01 (-0600)  diagnostics      return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/flask_caching/__init__.py", line 475, in decorated_function
10.11.21 19:26:01 (-0600)  diagnostics      rv = f(*args, **kwargs)
10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/hw_diag-1.0-py3.10.egg/hw_diag/views/diagnostics.py", line 44, in get_diagnostics_json
10.11.21 19:26:01 (-0600)  diagnostics      diagnostics = read_diagnostics_file()
10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/hw_diag-1.0-py3.10.egg/hw_diag/views/diagnostics.py", line 32, in read_diagnostics_file
10.11.21 19:26:01 (-0600)  diagnostics      perform_hw_diagnostics()
10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/hw_diag-1.0-py3.10.egg/hw_diag/tasks.py", line 42, in perform_hw_diagnostics
10.11.21 19:26:01 (-0600)  diagnostics      diagnostics = fetch_miner_data(diagnostics)
10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/hw_diag-1.0-py3.10.egg/hw_diag/utilities/miner.py", line 12, in fetch_miner_data
10.11.21 19:26:01 (-0600)  diagnostics      raise Exception("Unable to fetch miner peerbook from miner container "
10.11.21 19:26:01 (-0600)  diagnostics  Exception: Unable to fetch miner peerbook from miner container via JSON RPC API. Exception: Unable to connect to miner http://helium-miner:4467
10.11.21 19:26:11 (-0600)  diagnostics  DEBUG:flask_caching.backends.simplecache:get key 'view//initFile.txt' -> miss 
10.11.21 19:26:12 (-0600)  diagnostics  2021-11-11 01:26:12,084 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /usr/local/lib/pyth
```

**Comment by SebastianMaj** [comment]
> @SebastianMaj can you make sure [this invocation](https://github.com/NebraLtd/hm-diag/blob/master/hw_diag/tasks.py#L42) is also caught?
> 
> In testing, I am seeing:
> 
> ```
>  (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
> 10.11.21 19:26:01 (-0600)  diagnostics      rv = self.handle_user_exception(e)
> 10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
> 10.11.21 19:26:01 (-0600)  diagnostics      rv = self.dispatch_request()
> 10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
> 10.11.21 19:26:01 (-0600)  diagnostics      return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
> 10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/flask_caching/__init__.py", line 475, in decorated_function
> 10.11.21 19:26:01 (-0600)  diagnostics      rv = f(*args, **kwargs)
> 10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/hw_diag-1.0-py3.10.egg/hw_diag/views/diagnostics.py", line 44, in get_diagnostics_json
> 10.11.21 19:26:01 (-0600)  diagnostics      diagnostics = read_diagnostics_file()
> 10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/hw_diag-1.0-py3.10.egg/hw_diag/views/diagnostics.py", line 32, in read_diagnostics_file
> 10.11.21 19:26:01 (-0600)  diagnostics      perform_hw_diagnostics()
> 10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/hw_diag-1.0-py3.10.egg/hw_diag/tasks.py", line 42, in perform_hw_diagnostics
> 10.11.21 19:26:01 (-0600)  diagnostics      diagnostics = fetch_miner_data(diagnostics)
> 10.11.21 19:26:01 (-0600)  diagnostics    File "/usr/local/lib/python3.10/site-packages/hw_diag-1.0-py3.10.egg/hw_diag/utilities/miner.py", line 12, in fetch_miner_data
> 10.11.21 19:26:01 (-0600)  diagnostics      raise Exception("Unable to fetch miner peerbook from miner container "
> 10.11.21 19:26:01 (-0600)  diagnostics  Exception: Unable to fetch miner peerbook from miner container via JSON RPC API. Exception: Unable to connect to miner http://helium-miner:4467
> 10.11.21 19:26:11 (-0600)  diagnostics  DEBUG:flask_caching.backends.simplecache:get key 'view//initFile.txt' -> miss 
> 10.11.21 19:26:12 (-0600)  diagnostics  2021-11-11 01:26:12,084 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /usr/local/lib/pyth
> ```

https://github.com/NebraLtd/hm-diag/blob/sebastianmaj/miner-json-rpc-exceptions/hw_diag/utilities/miner.py

This is already being caught in a catch exception I put in 6 days ago, it's just not in the master branch yet.

**Comment by SebastianMaj** [comment]
[Fix: Ensure miner exceptions are caught #212](https://app.zenhub.com/workspace/o/nebraltd/hm-diag/issues/212)

This PR handles exceptions more gracefully, it catches all exceptions that are thrown by the miner and handles them properly to avoid having errors halting the process.

[Fix: Add timeout to request on helium api #217](https://github.com/NebraLtd/hm-diag/pull/217)

This PR solves the Error 500 related to the chain halt. With the chain halt we were unable to communicate with the helium api which was causing the miner to timeout on attempting to hit diagnostics.

**Comment by marvinmarnold** [comment]
@SebastianMaj great work. Can you point the [next testnet release](https://github.com/NebraLtd/helium-miner-software/pull/224) to the newest hm-diag commit SHA?

**Comment by SebastianMaj** [comment]
@marvinmarnold I updated the hm-diag SHA to the latest merge in docker-compose on @shawaj branch
