### ISSUE TITLE
Decomission /initFile.txt in favor of a robust /json

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#207]
We currently rely on `/initFile.txt` for countless checks, as well as for manufacturing. This is largely for legacy reasons. After a discussion with @marvinmarnold, we decided to sunset the entire `/initFile.txt` end-point in favor of a robust `/json` end-point.

- Ensure all services use /json instead of /initFile.
- Use DiagnosticsReport instead of raw dict.

**Comment by marvinmarnold** [comment]
This is being closed as all the details have been added to https://github.com/NebraLtd/Hotspot-Production-Tool/issues/28
