### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#223]
Following on from #212 I'm not sure the way this is handled is particularly great.

For example, killing the miner container and then loading diagnostics shows this:
![Screenshot_20211118-052439_Chrome](https://user-images.githubusercontent.com/3359418/142357242-8c6058ae-02de-45ba-9af1-a18a7bfcbf94.jpg)

However, lots of the data can still be displayed, and there's no reason why the JSON should return an error for everything when it still can provide useful data and just errors on the unreachable info due to miner container being down for example.

We should just display all the data we can and only show error messages for individually missing info on those specific lines with specific error messages.

Cc @marvinmarnold @SebastianMaj

**Comment by shawaj** [comment]
Relates to #204 and #207

**Comment by KevinWassermann94** [comment]
I have removed some bits in the following with xxxx for security reasons, but you get the idea

{
  "diagnostics_passed": false,
  "errors": [
    "W0"
  ],
  "RPI": "00000000594xxxx",
  "raspberry_pi_serial_number": "00000000594xxxxx",
  "ECC": true,
  "E0": "00:BD:27:XX:XX:XX",
  "eth_mac_address": "00:BD:27:XX:XX:XX",
  "W0": "Failed to find filecontaining miner mac address.Exception: [Errno 2] No such file or directory: '/sys/class/net/wlan0/address'",
  "wifi_mac_address": "Failed to find filecontaining miner mac address.Exception: [Errno 2] No such file or directory: '/sys/class/net/wlan0/address'",
  "BN": "weathered-pond",
  "BALENA_DEVICE_NAME_AT_INIT": "weathered-pond",
  "ID": "ca4471543790929984d0627cbbd73c92",
  "BALENA_DEVICE_UUID": "ca4471543790929984d0627xxxxxx",
  "BA": "HELIUM-TESTNET",
  "BALENA_APP_NAME": "HELIUM-TESTNET",
  "FR": "868",
  "FREQ": "868",
  "FW": "2021.11.17.2-1",
  "FIRMWARE_VERSION": "2021.11.17.2-1",
  "VA": "NEBHNT-OUT1",
  "VARIANT": "NEBHNT-OUT1",
  "BT": true,
  "LTE": true,
  "LOR": true,
  "lora": true,
  "OK": "112osQb9FtajkbrLnahUiCPBQVu8",
  "onboarding_key": "112osQb9FtajkbrLna",
  "PK": "112osQb9FtajkbrLnahUiCPBQVu",
  "public_key": "112osQb9FtajkbrLnahUiCPBQ",
  "PF": true,
  "legacy_pass_fail": true
}

**Comment by vpetersson** [comment]
ping @marvinmarnold @SebastianMaj

**Comment by KevinWassermann94** [comment]
18.11.21 14:59:51 (+0100)  diagnostics      if int(diagnostics['MH']) > (int(diagnostics['BCH']) - 500):
18.11.21 14:59:51 (+0100)  diagnostics  TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

Seeing a similar error to this on production e.g. https://dashboard.balena-cloud.com/devices/105d1e8b787af6cfd83488a1bb26033a/summary

https://dashboard.balena-cloud.com/devices/37e7dcd714349f64f1745f38e49ee12b/summary

**Comment by justkidding96** [comment]
@KevinWassermann94 Is it possible to access the miner through SSH? I tried but I have no access because of the public key.

**Comment by KevinWassermann94** [comment]
@marvinmarnold Found another one

18.11.21 16:33:13 (+0100)  diagnostics      if int(diagnostics['MH']) > (int(diagnostics['BCH']) - 500):
18.11.21 16:33:13 (+0100)  diagnostics  TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

https://dashboard.balena-cloud.com/devices/77dfbba0610b4b5cba060d7e5b315621/summary

**Comment by marvinmarnold** [comment]
I've identified the issue:

The [request](https://github.com/NebraLtd/hm-diag/blob/master/hw_diag/utilities/blockchain.py#L13) for Helium blockchain height is failing sometimes. You can tell from the logs:

```
18.11.21 09:57:58 (-0600)  diagnostics  DEBUG:urllib3.connectionpool:https://api.helium.io:443 "GET /v1/blocks/height HTTP/1.1" 429 458
```

The `429` near the end is the HTTP response code. 429 means [too many requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429). What's extra weird is that `curl https://api.helium.io/v1/blocks/height` works on devices that experiencing this issue.

Some code like this lets the diagnostics be constructed successfully:

```
@@ -21,3 +21,6 @@ def get_helium_blockchain_height():
                 "Not found value from key ['data']['height'] in json"
             )
         return result
+    else:
+        print("Request failed %s" % result)
+        return -1
```
But from a user perspective, what value do we want to display when the height cannot be calculated? @KevinWassermann94

**Comment by KevinWassermann94** [comment]
@marvinmarnold The best would be to show something like: Unable to receive blockchain information from the API, but not sure if we can do that

**Comment by marvinmarnold** [comment]
I've updated the view to show `Not Available` that's what we were already using for other failure modes. Will that do? https://github.com/NebraLtd/hm-diag/pull/229/commits/c6e2994fdf9d9f146e583dc7dad7912df638f59f

**Comment by KevinWassermann94** [comment]
That should work. This should hopefully not happen too often anyway as it seems to be an upstream issue with the API

**Comment by marvinmarnold** [comment]
Also, I think the real fix is giving /json the same attention we gave /initFile with https://github.com/NebraLtd/hm-diag/issues/207. The current code is pretty fragile, even after https://github.com/NebraLtd/hm-diag/pull/229.

**Comment by SebastianMaj** [comment]
> Also, I think the real fix is giving /json the same attention we gave /initFile with #207. The current code is pretty fragile, even after #229.

I can jump on this if we would like to include #207 in the current sprint. I noticed that when an error occurs it doesn't output the json diagnostics. For example, when the diagnostics page was displaying the int() casting on a None type error that's all the /json endpoint served as well. 

The majority of it is already completed with the exceptions added to hm-diag, all that's missing to push it to completion seems to be that it's still displaying only the error message instead of the whole diagnostics when an error occurs when the desired result is to only display error messages in specific keys but still load up the diagnostics json.

**Comment by shawaj** [comment]
@justkidding96 no SSH access I'm afraid no

**Comment by shawaj** [comment]
@SebastianMaj it might be useful to have more "user friendly" error messages as well potentially on the front-end and only have the more detailed error messages in the debug logs perhaps

**Comment by SebastianMaj** [comment]
> @SebastianMaj it might be useful to have more "user friendly" error messages as well potentially on the front-end and only have the more detailed error messages in the debug logs perhaps

I'll create an issue for this that stems off of #204 for more user-friendly error messages per diagnostic key
