### ISSUE TITLE
Feature request: Please add temperature, cpu and storage monitoring on the diag page

### ISSUE THREAD

**Issue by lance36** [NebraLtd/hm-diag#224]
As per title it would be very useful to have these information in the diag page.

**Comment by justkidding96** [comment]
@lance36 You mean if the diag is finally reachable? The only thing I get is a 500 error.

**Comment by kf5gxz** [comment]
I think that's a great idea

**Comment by kf5gxz** [comment]
What needs to be done to make this happen?

**Comment by lance36** [comment]
To add to this, with the dashboard often (and understandably) being not accessible, and most data not being real-time, we could really benefit from being able to gauge the status of the miner from the local  diag page.
Expecially in situations like the recent blockchain halts where some miner would go out of memory and bootloop causing it to overheat and possibly reducing hardware components life span.

**Comment by marcodlima** [comment]
This would be very usefull!
