### ISSUE TITLE
Feature request: ability to change network settings without bluetooth.

### ISSUE THREAD

**Issue by millerz1897** [NebraLtd/hm-diag#226]
Having difficulty (all versions including latest 11.11 update) connecting and maintaining wireless connectivity via helium app ( last 3 versions including the moat recent 3.8.0). Would be very nice to have an administrative interface over hardwired Ethernet to adjust, reboot, etc.

**Comment by millerz1897** [comment]
@shawaj - Agree, and share the concern.

Perhaps a reset button or console access or something?  Perhaps even a priority ticket to support?

Would be best to fix the helium app / Nebra integration configuration to work as intended but until that happens it's a pretty frustrating thing.  Especially as I think about scaling up from one node...

**Comment by shawaj** [comment]
Duplicate of #554
