### ISSUE TITLE
Feature request: Enhance Bluetooth antenna for Outdoor units

### ISSUE THREAD

**Issue by millerz1897** [NebraLtd/hm-diag#228]
While I know there are issues wiht the Helium/Nebra integration.  Having trouble maintaining a good connection from Mobile phone to nebra device via bluetooth.

Believe that distance to the unit is a customer problem but an enhanced antenna (just as WiFi is done) outside of the metal housing would help, or at least help remove one variable from diagnosing the device.

**Comment by shawaj** [comment]
We have no plans to fix this on the current design.

Having said that our upcoming Rockchip based design will use a single antenna for both WiFi and Bluetooth so will have this functionality by default
