### ISSUE TITLE
Change Headers on API requests

### ISSUE THREAD

**Issue by lance36** [NebraLtd/hm-diag#232]
Hi, 

Now that the error-handling is solved I've noticed the Helium API dosent like python-requests without headers and is recently only responding with HTTP error `429`:
```
>>> import requests
>>> HELIUM_MINER_HEIGHT_URL = 'https://api.helium.io/v1/blocks/height'
>>> result = requests.get(HELIUM_MINER_HEIGHT_URL, timeout=5)
>>> result
<Response [429]>
```

I believe that is why the hotspots are showing an error right now, while the API is up and stable:
![image](https://user-images.githubusercontent.com/3243764/142648999-7ac02981-0178-4bc8-abaf-f3ad66acbf97.png)
![image](https://user-images.githubusercontent.com/3243764/142649050-279b6dd1-ec31-40d1-943d-e8335b201e6c.png)

Adding any different header to the request seems to solve the issue:
```
>>> headers = {'user-agent': 'Mozilla/5.0 (X11; U; Linux i686; it; rv:1.9.0.10) Gecko/2009042513 Ubuntu/8.04 (hardy) Firefox/3.0.10',}
>>> result = requests.get(HELIUM_MINER_HEIGHT_URL, headers=headers, timeout=5)
>>> result
<Response [200]>
>>> result.json()['data']['height']
1103908
```

Here: 
https://github.com/NebraLtd/hm-diag/blob/b1210ec87ab347d2a1ae8fe358b30fbf33bcb317/hw_diag/utilities/blockchain.py#L18-L19

**Comment by vpetersson** [comment]
Nice find @lance36

**Comment by marvinmarnold** [comment]
@SebastianMaj FYI we shouldn't close issues until they've reached production.
