### ISSUE TITLE
Improve diagnostics page messages when Helium API and miner RPC unavailable

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#235]
**User Story**
As a diagnostics user, I should be able to clearly differentiate miner errors from Helium API errors so that I have a better sense of what is going wrong.

**Notes**
- We were previously using negative values to indicate errors but have since started using `None` values.

[Slack convo](https://nebraltd.slack.com/archives/C0XGF69SN/p1637336138314900?thread_ts=1637334745.312300&cid=C0XGF69SN)

**Acceptance Criteria**
- Sync Percentage: Remove [Not Available](https://github.com/NebraLtd/hm-diag/blob/00c716dd4980e35ac7436d9f59aebb17bec07535/hw_diag/templates/diagnostics_page.html#L53) from template. This is now no longer possible (we use None instead of -1). 
- Sync Percentage: Add `Miner RPC Unavailable`
- Sync Percentage: Rename `Helium API Not Available` to `Helium API Unavailable`
- Height Status: Rename `Not Available` to `Miner RPC Unavailable` 
- Height Status: Add `Helium API Unavailable`.

**Comment by shawaj** [comment]
Related to #195
