### ISSUE TITLE
Feature Request: Add additional system diagnostic and support information.

### ISSUE THREAD

**Issue by millerz1897** [NebraLtd/hm-diag#240]
Recommend this upgrade be added to the local diagnostics page.

I think it might help a lot of people be more aware of what is going on and reduce frustration levels.

I've noticed that the Nebra Dashboard SaaS has additional information on the device such as CPU memory, and storage usage.

Like block sync, A quick putt to the NEBRA API could also state the release version and the local dashboard could display the installed and the current version with a quick API call to a separate Nebra service.

In addition, like the "Helium Address"  links to useful sites, and a short blurb on why/how they are useful could be helpful too.  

https://status.helium.com - To see API status, current issues, and subscribe if they like.

https://app.heliumstatus.io very helpful for ping test of both the local port and the ping test to the API location.

**Comment by shawaj** [comment]
Generally I completely agree with your suggestions :-)

Some of this is duplicated in #41 

We also have already got features which will allow more data to pull through to the dashboard from the miners.

Lastly, we also soon will have a watchdog container that will enable some more of these requested features https://github.com/NebraLtd/hm-watchdog
