### ISSUE TITLE
New endpoint to read hm-diag version

### ISSUE THREAD

**Issue by kashifpk** [NebraLtd/hm-diag#244]
In order to confirm the hm-diag version a miner is running, expose a new endpoint (perhaps `/info`?) To return the version of hm-diag. The version is going to be the git hash of the hm-diag commit that is in use.

basically pass on the GIT_HASH from GitHub Action as a build argument, and parse the build argument onto a file on disk. Then we can read the value from disk and return it from the endpoint.

Also should add functionality in HPT to query `/info` URL before /initFile.txt and display the version in console and in logs. 

This should allow us to be certain that production is using the latest images and errors encountered are not because of older firmware images still being in use in production.

**Comment by kashifpk** [comment]
@vpetersson or may be `/version` is a better option?

**Comment by vpetersson** [comment]
Yeah i'd use `/version` and perhaps do something like a JSON with the diag hash and the miner version.

**Comment by kashifpk** [comment]
@vpetersson - Why can't we just set and environment variable in docker compose file here: https://github.com/NebraLtd/helium-miner-software/blob/master/docker-compose.yml#L62 ? We're already setting the `FIRMWARE_VERSION` so we could just add `DIAGNOSTICS_VERSION` here too. As we do specify the git hash on [Line 60](https://github.com/NebraLtd/helium-miner-software/blob/master/docker-compose.yml#L60) any way?

**Comment by vpetersson** [comment]
I mean, that's fair. The idea was that we will remove `FIRMWARE_VERSION` fully later on in favor of asking the miner directly (over the RPC you're using above).

**Comment by kashifpk** [comment]
Yes but for now it works? Since we're the ones updating the docker-compose and all we wanted for now was to confirm that the miner was running the version we expect.

**Comment by kashifpk** [comment]
> but yes, if we can automate this step, that would be fine.

It seems like manual work for now but perhaps later these can be defined as ansible variables (since docker-compose files can't define variables within them and rely on using `.env` files) then we could just build the docker-compose itself based on a template compose file and filling in these values. But that is another issue :-)

**Comment by vpetersson** [comment]
Hmm, not sure if Ansible is the right tool for the job here. I think an easier solution is to just use say a JINJA2 template and build the file on demand.

**Comment by kashifpk** [comment]
yeah that would be simpler. So we can use the current manual approach for now and automate later.

**Comment by vpetersson** [comment]
Hmm, i wonder if we could use https://docs.docker.com/compose/environment-variables/ instead and just define them in a `.env` file instead and be able to re-use them all over the place in the `docker-compose.yml` file.

**Comment by kashifpk** [comment]
yeah if we want to do that we should probably put other variables like `FIRMWARE_VERSION`, `DBUS_SYSTEM_BUS_ADDRESS` and `DBUS_SESSION_BUS_ADDRESS` in there too.

**Comment by kashifpk** [comment]
TBD: Point to this commit in helium-miner-software docker-compose.yml file.

**Comment by kashifpk** [comment]
@vpetersson @shawaj - Should we include versions for other components in this endpoint? Currently we provide version for `FIRMWARE_VERSION` and `DIAGNOSTICS_VERSION`. We can provide versions for `CONFIG_VERSION`, `PKTFWD_VERSION`,
`MINER_VERSION` and
`UPNP_VERSION`

**Comment by shawaj** [comment]
We don't need it currently AFAIK but may be useful in the future I guess

**Comment by vpetersson** [comment]
I mean, we basically get it for free after moving to the templated version, so let's include it too. No harm in adding it, but it might help with troubleshooting.
