### ISSUE TITLE
Update BtLteDiagnostic() to use the new method for detecting BT and LTE devices

### ISSUE THREAD

**Issue by posterzh** [NebraLtd/hm-diag#252]
There is a resolved issue for better detecting BT and LTE interface(https://github.com/nebraltd/hm-diag/issues/96).
This logic also needs to be added to `BtLteDiagnostic()`(https://github.com/NebraLtd/hm-diag/blob/00c716dd4980e35ac7436d9f59aebb17bec07535/hw_diag/diagnostics/bt_lte_diagnostic.py#L37).

Reference:
https://github.com/NebraLtd/hm-diag/pull/242#pullrequestreview-816965206

**Comment by shawaj** [comment]
@marvinmarnold ah ok makes sense 👍
