### ISSUE TITLE
key provisioning doesn't work on rockpi

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#253]
key provisioning does not occur automatically on rockpi and diag hangs on `Diagnostics have not yet run, please try again in a few minutes`

**Comment by shawaj** [comment]
this seems to be the issue:

https://github.com/NebraLtd/hm-pyhelper/blob/1558a71f3614d23d36b1bdf227bab104c8c9c296/hm_pyhelper/miner_param.py#L105-L110

**Comment by vpetersson** [comment]
I have a feeling that this is related to the `i2c` mapping [here](https://github.com/NebraLtd/hm-pyhelper/blob/master/hm_pyhelper/miner_param.py#L29-L31). I tested this by hand on the regular RockPi image, but we haven't end-to-end tested this feature on Balena yet.

**Comment by shawaj** [comment]
@vpetersson the provisioning works, just not automatically because of the bit I shared above

**Comment by vpetersson** [comment]
I've spotted the bug. Will Create an issue for it.

**Comment by vpetersson** [comment]
Tracked down the bug and added https://github.com/NebraLtd/hm-pyhelper/issues/72 to solve it. Should be a quick fix.

**Comment by shawaj** [comment]
Closed by https://github.com/NebraLtd/helium-miner-software/pull/286
