### ISSUE TITLE
Healthcheck fails - wget: not found

### ISSUE THREAD

**Issue by iankaufmann** [NebraLtd/hm-diag#273]
Firmware Version | 2021.12.14.0

I noticed that the diagnostics container was crashing often, and always in a (Starting) state.

Digging into `balena-engine inspect` I saw this:

```
"Health": {
    "Status": "starting",
    "FailingStreak": 4,
    "Log": [
        {
            "Start": "2021-12-19T01:48:09.391672934Z",
            "End": "2021-12-19T01:48:10.755888085Z",
            "ExitCode": 1,
            "Output": "/bin/sh: 1: wget: not found\n"
        },
        {
            "Start": "2021-12-19T01:50:17.94280988Z",
            "End": "2021-12-19T01:50:19.17836156Z",
            "ExitCode": 1,
            "Output": "/bin/sh: 1: wget: not found\n"
        },
        {
            "Start": "2021-12-19T01:52:19.216071717Z",
            "End": "2021-12-19T01:52:20.496799759Z",
            "ExitCode": 1,
            "Output": "/bin/sh: 1: wget: not found\n"
        },
        {
            "Start": "2021-12-19T01:54:20.536884687Z",
            "End": "2021-12-19T01:54:21.996848867Z",
            "ExitCode": 1,
            "Output": "/bin/sh: 1: wget: not found\n"
        },
        {
            "Start": "2021-12-19T01:56:22.043875034Z",
            "End": "2021-12-19T01:56:23.205485664Z",
            "ExitCode": 1,
            "Output": "/bin/sh: 1: wget: not found\n"
        }
    ]
}
```

I'm not sure if this is causing other issues, but it appeared to be causing the miner to go unresponsive at least once an hour and until I enabled SSH to start poking around, I was having to power cycle it to get it to come back (for a short time).

After `exec` into the container and installing `wget` the container stopped crashing and reports (Healthy) state:

```
"Health": {
    "Status": "healthy",
    "FailingStreak": 0,
    "Log": [
        {
            "Start": "2021-12-19T01:58:23.246580687Z",
            "End": "2021-12-19T01:58:24.725130115Z",
            "ExitCode": 1,
            "Output": "/bin/sh: 1: wget: not found\n"
        },
        {
            "Start": "2021-12-19T02:00:24.773121117Z",
            "End": "2021-12-19T02:00:27.073970549Z",
            "ExitCode": 0,
            "Output": "eyJkaWFnbm9zdGljc19wYXNzZWQiOiB0cnVlLCAiZXJyb3JzIjogW10sICJzZXJpYWxfbnVtYmVyIjogIjAwMDAwMDAwZmVkMDMxNjgiLCAiRUNDIjogdHJ1ZSwgIkUwIjogIkYwOjRDOkQ1OkFDOjFFOkUzIiwgImV0aF9tYWNfYWRkcmVzcyI6ICJGMDo0QzpENTpBQzoxRTpFMyIsICJXMCI6ICJDQzo3OTpDRjo2QTozMjo2MCIsICJ3aWZpX21hY19hZGRyZXNzIjogIkNDOjc5OkNGOjZBOjMyOjYwIiwgIkJOIjogImhhdW50ZWQtd2luZCIsICJCQUxFTkFfREVWSUNFX05BTUVfQVRfSU5JVCI6ICJoYXVudGVkLXdpbmQiLCAiSUQiOiAiYTllMDRmMzQ0YjllMmM4N2YyYmZmMTE5NDhlMTNkMWEiLCAiQkFMRU5BX0RFVklDRV9VVUlEIjogImE5ZTA0ZjM0NGI5ZTJjODdmMmJmZjExOTQ4ZTEzZDFhIiwgIkJBIjogIkhFTElVTS1JTkRPT1ItOTE1IiwgIkJBTEVOQV9BUFBfTkFNRSI6ICJIRUxJVU0tSU5ET09SLTkxNSIsICJGUiI6ICI5MTUiLCAiRlJFUSI6ICI5MTUiLCAiRlciOiAiMjAyMS4xMi4xNC4wIiwgIkZJUk1XQVJFX1ZFUlNJT04iOiAiMjAyMS4xMi4xNC4wIiwgIlZBIjogIk5FQkhOVC1JTjEiLCAiVkFSSUFOVCI6ICJORUJITlQtSU4xIiwgIkJUIjogdHJ1ZSwgIkxURSI6IGZhbHNlLCAiTE9SIjogdHJ1ZSwgImxvcmEiOiB0cnVlLCAiT0siOiAiMTFTZEFidmJBOEdZcm5jdTh5UWhOVEFQY0NNRjRxcUNVR29XOGVzNW1nMlZjY1NFN2RnIiwgIm9uYm9hcmRpbmdfa2V5IjogIjExU2RBYnZiQThHWXJuY3U4eVFoTlRBUGNDTUY0cXFDVUdvVzhlczVtZzJWY2NTRTdkZyIsICJQSyI6ICIxMVNkQWJ2YkE4R1lybmN1OHlRaE5UQVBjQ01GNHFxQ1VHb1c4ZXM1bWcyVmNjU0U3ZGciLCAicHVibGljX2tleSI6ICIxMVNkQWJ2YkE4R1lybmN1OHlRaE5UQVBjQ01GNHFxQ1VHb1c4ZXM1bWcyVmNjU0U3ZGciLCAiUEYiOiB0cnVlLCAibGVnYWN5X3Bhc3NfZmFpbCI6IHRydWV9"
        }
    ]
}
```

It has now been up for 5 hours without crashing.

**Comment by vpetersson** [comment]
This is interesting. Last time we spoke to Balena, these health checks were not implemented and silently ignored. Based on the above logs, this is not running on any of our managed devices, so I presume you're running this on your own fleet. Whilst this is unsupported, I'm still interested in what version of balenaOS etc you're using.

**Comment by iankaufmann** [comment]
> This is interesting. Last time we spoke to Balena, these health checks were not implemented and silently ignored. Based on the above logs, this is not running on any of our managed devices, so I presume you're running this on your own fleet. Whilst this is unsupported, I'm still interested in what version of balenaOS etc you're using.

This is on a Nebra unit from Parley Labs.

I have had nothing but trouble with it, so I added a public key to config.json in an attempt to try to figure out what is going on with it.

Are you saying there is something different about this unit?

**Comment by vpetersson** [comment]
I've resolved this in https://github.com/NebraLtd/hm-diag/pull/274. I'm still not convinced that this fix does anything, but it shouldn't hurt at least.

**Comment by iankaufmann** [comment]
> I've resolved this in https://github.com/NebraLtd/hm-diag/pull/274. I'm still not convinced that this fix does anything, but it shouldn't hurt at least.

Hard for me to say.  I know my way around Linux/Docker, but only just got my miner a week ago, so I'm just exploring this thing blind as of a few days ago.

What I have experienced with the Nebra unit so far is several times a day it just goes completely unresponsive.  (No web UI, no ping, not syncing)

At first it looked to be overheating (80C-85C according to dashboard.nebra.com), so I re-pasted the heatsink and pointed an external fan on it.  (This is with it being winter weather in an attic).

When that didn't help, I cloned the eMMC to a SanDisk Extreme A2 SD card.

When that didn't help, I found a thread that showed how to gain SSH, and just started looking at any logs I could find, and that led me to seeing that the diagnostics container seemed to never leave (starting) state, and only ever had an uptime of 5 minutes.  After installing wget, now it has a uptime that matches the rest of the containers.

Now it crashes less frequently, but still a couple times a day.  (I monitor the /json endpoint with a script)

I noticed that when it crashes, if I'm still connected to SSH, I don't get booted from SSH.  So, now I know that it's not a wifi/network problem.

However, during this time, I cannot ping anything from the Nebra.  No api.helium.io, no google.com, nothing.

If I run `systemctl restart NetworkManager`, it comes back and everything starts working again.

So something is still crashing NetworkManager quite frequently.

Sorry if this sounds crazy, but I am just trying to make sense of a problem with the tools and knowledge that I have (which is limited in the scope of this project).

I know that this isn't a support forum, but I felt that I had more info that is relevant here than a typical "help me" post.

I have contacted Parley and they only wanted me to return it to them for troubleshooting, and I said no way after waiting 9 months to get this far.  Seemed like there was nothing they could do that I couldn't do myself while at least keeping it mining in the meantime.

Thanks for your interest.  Let me know if you want any more info from my unit.

**Comment by vpetersson** [comment]
Thanks for the investigation, @iankaufmann. Nothing obvious springs to mind. I would however strongly recommend that you restore the device to the original state (i.e. the original storage) etc. 

I'd also recommend turning off your monitoring of `/json` as that will add unnecessary load to the device, which might hinder the device from restoring snapshots from Helium. This is already a very resource intense process and is maxing out the device resources for an extended period of time.

After doing the above, please leave the device for a day or so to give it enough time to recover. Normally, the process only takes an hour or two, but in some cases, it might take longer.

**Comment by iankaufmann** [comment]
Well, I can't say I didn't expect an answer like that.  I can appreciate why you would suggest that.  Obviously, I too would prefer if it just worked out of the box, but in my experience so far, it hasn't.  I didn't start poking around for fun.

Right now, it is fully synced and is witnessing, challenging, and beaconing (at least after the 2021.12.14.0-1 update).  

It freezes up once or twice a day, at which point I restart NetworkManager and then it's right back in action.

This is preferable to me vs. just doing nothing and letting it get 100s or 1000s of blocks out of sync, and then waiting for that to catch up.  Basically the longer it's down, the longer it takes to sync and get back up.

It also would be pretty surprising/disappointing if loading the diagnostics (either in the browser or from /json) once every 5 minutes would crash this thing.  I would understand if it were in the middle of a massive sync, but like I said, it's fully caught up.

Honestly, the few days that I've been on top of this, keeping it synced and with minimal downtime are the only days that it has actually performed and earned anything.

I can see why you would assume that I have screwed it up by what I've done, but for real, all I have done inside the OS is install wget into the diagnostics container, look at logs, and restart NetworkManager when it needs it.  

Parley/Nebra is actually shipping me a replacement eMMC because that was the only thing they could think to do.

When I get that, I may put that back in and let it rebuild, but in the meantime, I'd like to keep it mining now that it is actually working for the most part.

I have a RAK that I plugged in 3 months ago and haven't touched and it works day in and day out.  I know I'm not the only one having unexplained issues with Nebra.  Just wanted to share what my experience has been.   Thanks for the chat.

**Comment by shawaj** [comment]
Reopening until merged into production. Moving to testnet now

**Comment by shawaj** [comment]
https://github.com/NebraLtd/helium-miner-software/pull/319

**Comment by shawaj** [comment]
@iankaufmann so you think network manager is crashing a couple of times a day?

Don't suppose you could email support@nebra.com with the QR code label from your device? And reply back here with the ticket number?

Interested to speak to balena and see if they have any thoughts 👍

**Comment by iankaufmann** [comment]
Hey @shawaj!

I've just submitted the ticket (#324258).

I tried to sum up everything I've experienced in the ticket with more detail.

In writing it out, I realized that saying that NetworkManager itself is crashing might not be technically correct, since (as mentioned in the ticket) the output of `systemctl status NetworkManager` shows that it's Active and not down or crashed.  

It's just that `systemctl restar NetworkManager` is what fixes the issue and allows it to reach the internet again.

This is what I see in the logs before restarting it:
```
journalctl -f --no-pager -n 400 -u balena.service
Dec 18 23:06:14 a9e04f3 fffe26375285[1471]: [error]   LogBackend: unexpected error: Error: socket hang up
Dec 18 23:06:14 a9e04f3 fffe26375285[1471]: [error]         at connResetException (internal/errors.js:608:14)
Dec 18 23:06:14 a9e04f3 fffe26375285[1471]: [error]       at TLSSocket.socketOnEnd (_http_client.js:460:23)
Dec 18 23:06:14 a9e04f3 fffe26375285[1471]: [error]       at TLSSocket.emit (events.js:322:22)
Dec 18 23:06:14 a9e04f3 fffe26375285[1471]: [error]       at endReadableNT (_stream_readable.js:1187:12)
Dec 18 23:06:14 a9e04f3 fffe26375285[1471]: [error]       at processTicksAndRejections (internal/process/task_queues.js:84:21)
Dec 18 23:06:22 a9e04f3 f097ed622d8f[1471]: INFO: [down] PULL_ACK received in 0 ms
Dec 18 23:06:24 a9e04f3 fffe26375285[1471]: [api]     GET /v1/healthy 200 - 42.214 ms
Dec 18 23:06:24 a9e04f3 fffe26375285[1471]: [info]    VPN connection is not active.
Dec 18 23:06:31 a9e04f3 fffe26375285[1471]: [info]    Waiting for connectivity...
```

So it's losing connection to some sort of internal VPN and then never reconnecting... and restarting NetworkManager must be fixing that?


Thanks for the interested, happy to answer any other questions you have!

**Comment by st3fan87** [comment]
Don't know if it's related but since last Friday my indoor nebra also has an unstable dashboard. 

It occurs only when sync is not 100%. 

The device will automatically reboot multiple times, dashboard available/unavailable, long periods of errors in dashboard saying Miner RPC Unavailable. 

after a lot of reboots the nebra is finally able to sync again and starts working (6 hours straight now)

Don't know if it's related to this topic but maybe it helps. Also I've seeing multiple other people having the same behavior

**Comment by shawaj** [comment]
@st3fan87 yours sounds like an issue with snapshot loading and syncing rather than this. The diagnostics will always struggle to load when this is happening

**Comment by st3fan87** [comment]
> @st3fan87 yours sounds like an issue with snapshot loading and syncing rather than this. The diagnostics will always struggle to load when this is happening

Ah yes, is there anything I could do to improve it?
