### ISSUE TITLE
Include AddGateway transaction in /initFile payload

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#283]
Pass this through to the dashboard's registration payload.

Ensure writability: mount | grep boot
/dev/mmcblk0p1 on /mnt/boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)

No longer require nebra.json to be on device. HPT will send a request with the necessary payload.

**Acceptance Criteria**

- Add Nebra's manufacturing public key corresponding to ihub.json.asc.
- POST /v1/add_gateway_txn should:
  - Should accept ihub.json.asc as a param. Either as string contents, or file. 
  - If ihub.json.asc's signature is validated, continue, otherwise return error.   
  - If valid, generate `shipping_destination_add_gateway_txn` by invoking https://github.com/NebraLtd/hm-pyhelper/issues/91 and supplying a random wallet from the list.
   - Always return Diagnostics report as payload.
   - Return 404 if there is an error.
   - `shipping_destination_add_gateway_txn` must be a JSON that includes the transaction and wallet ID used, presumably it [should look like](https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/hotspot-integration-testing#generate-an-add-hotspot-transaction):

```
{
  "address": "11TL62V8NYvSTXmV5CZCjaucskvNR1Fdar1Pg4Hzmzk5tk2JBac",
  "fee": 65000,
  ~"mode": "full",~ (ignore, not relevant)
  "owner": "14GWyFj9FjLHzoN3aX7Tq7PL6fEg4dfWPY8CrK8b9S5ZrcKDz6S",
  "payer": "138LbePH4r7hWPuTnK6HXVJ8ATM2QU71iVHzLTup1UbnPDvbxmr",
  "staking fee": 4000000,
  "txn": "CrkBCiEBrlImpYLbJ0z0hw5b4g9isRyPrgbXs9X+RrJ4pJJc9MkSIQA7yIy7F+9oPYCTmDz+v782GMJ4AC+jM+VfjvUgAHflWSJGMEQCIGfugfLkXv23vJcfwPYjLlMyzYhKp+Rg8B2YKwnsDHaUAiASkdxUO4fdS33D7vyid8Tulizo9SLEL1lduyvda9YVRCohAa5SJqWC2ydM9IcOW+IPYrEcj64G17PV/kayeKSSXPTJOMCEPUDo+wM="
}
```

**Comment by SebastianMaj** [comment]
Where are we pulling destination wallets array from? Is this something that will be added to the team model on dashboard or are we planning to pull it in from nebra.json?

**Comment by vpetersson** [comment]
This will be pulled in from Nebra.json

**Comment by SebastianMaj** [comment]
Is Nebra.json something that will be generated by hm-diag? I SSHed into my device on the latest firmware and the file does not exist at the moment

**Comment by vpetersson** [comment]
See https://github.com/nebraltd/hotspot-production-images/issues/26

**Comment by SebastianMaj** [comment]
> See [NebraLtd/hotspot-production-images#26](https://github.com/NebraLtd/hotspot-production-images/issues/26)

Thank you Viktor! This clarifies my confusion, I spoke with Marvin about it too and he pointed me in the right direction.

**Comment by marvinmarnold** [comment]
@kashifpk I think we need to add another validation to HPT, probably here: https://github.com/NebraLtd/Hotspot-Production-Tool/blob/5c6304433e5a36a9877738bf7fe60f39f2ccb126/app/src/hpt/payload_validator.py#L16

HPT needs to make sure that `destination_add_gateway_txn` is always set if `destination_name` is present. This is because, by design, hm-diag will only send `destination_add_gateway_txn` the very first time `initFile.txt` is invoked. At the end of the first invocation, `destination_wallets` is deleted from nebra.json. From hm-diag's perspective, it is normal to return `destination_name` without `destination_add_gateway_txn`. Only HPT can understand that this is an error.

**Comment by kashifpk** [comment]
> HPT needs to make sure that destination_add_gateway_txn is always set if destination_name is present. This is because, by design, hm-diag will only send destination_add_gateway_txn the very first time initFile.txt is invoked

@marvinmarnold So as soon as hpt gets the key `destination_add_gateway_txn` in `/initFile.txt` payload, it should temporarily store the payload somewhere? What happens if at that time there are other "manufacturing errors" present in diagnostics report (like the ECC error) that might go away on future retries?

**Comment by marvinmarnold** [comment]
Yes, HPT would have to store it in case it needs to retry `/initFile.txt` for other reasons. @vpetersson  do you agree?

**Comment by kashifpk** [comment]
We can do that but this seems like fragile logic considering how manufacturing behaves. If they see an error and remove the miner (while the error could have been fixed just by waiting) then the miner would need to be re-flashed causing more manufacturing delays.

Perhaps it would be better from hm-diag to delete `destination_wallets` only after receiving an acknowledgement from HPT? Like may be a POST to /initFile.txt? So HPT can acknowledge once the miner is registered and before printing the labels.

**Comment by marvinmarnold** [comment]
@kashifpk I agree that your proposal is superior. We're going to have a lot of headaches if destination_wallets is strictly deleted after first response.

**Comment by vpetersson** [comment]
@kashifpk so this does change the logic a fair bit though. At this point, all communication to hm-diag is read-only. If we implement this, that will change. Since the transaction is generated based on the TPM, a re-flashing shouldn't really change anything.

**Comment by kashifpk** [comment]
@vpetersson can you explain further? Do you mean we won't be able to generate the transaction again even if we re-flash the miner? Then this becomes the most critical part during manufacturing QC to ensure that once we have generated the transaction we don't loose it.

Another question would be related to the timing of when we generate the transaction? What happens when miner has errors that can be fixed by swapping components etc? Should the transaction be generated after HPT has determined that the miner is ready otherwise?

**Comment by vpetersson** [comment]
> @vpetersson can you explain further? Do you mean we won't be able to generate the transaction again even if we re-flash the miner? Then this becomes the most critical part during manufacturing QC to ensure that once we have generated the transaction we don't loose it.

No, what I mean is that I think we can re-generate this transaction as many times as we want. It's all done on the security chip, so reflashing device shouldn't have any impact. 

> Another question would be related to the timing of when we generate the transaction? What happens when miner has errors that can be fixed by swapping components etc? Should the transaction be generated after HPT has determined that the miner is ready otherwise?

The transaction is tied to the secure enclave, so if that is swapped, the transaction will be different (as well as the identity in Helium). Short of that, it shouldn't matter if other components are swapped.

**Comment by kashifpk** [comment]
> The transaction is tied to the secure enclave, so if that is swapped, the transaction will be different (as well as the identity in Helium). Short of that, it shouldn't matter if other components are swapped.

Ok in that case above suggestion should work nicely. At hm-diag side we'll just need to move the delete logic away from `GET /initFile.txt` and into a POST request. What is your opinion about moving the transaction generation logic away from `/initFile.txt` altogether? This logic of generating it the first time is kind of strange. Instead we could just simple add another endpoint for generating the transaction and then acknowledging it to remove the wallet from nebra.json. Something like

1.  HPT calls `/initFile.txt` payload and sees `destination_name` in response indicating that we need to generate the add gateway transaction.

2. Once HPT deems the miner to be ready (has no manufacturing errors), HPT requests transaction generation through:  `POST /gen_gateway_txn` with empty data. Using POST here because it's good REST practice otherwise could easily be GET.

3. HPT uses the received transaction payload to register device in dashboard and then acknowledges the transaction via `PUT /gen_gateway_txn/ack`. In response to this hm-diag deletes the wallet address. 

4. Any future calls to `/gen_gateway_txn` or `/gen_gateway_txn/ack` return 404 so this functionality does no remain available once miner passes manufacturing.
```

This operation gives us more control on when we want to generate the transaction.

**Comment by marvinmarnold** [comment]
Following up on the diagnostics API refactoring:

- FastAPI: I don't think we should make this migration this sprint. Would rather focus on the business logic we need this sprint, then do a FastAPI refactor in the near future.
- Versioned API: Can easily prefix the new txn endpoints with /v2/ for now until we add proper versioning with FastAPI.
-  Breaking up into smaller endpoints: I'm not clear what this will get us, need some convincing this is a priority.
- HTTP error codes: Makes a lot of sense to use these for the new endpoints. Is not obvious how we would do this with with `/json`. Goes back to the concept of `PF` and whether we can declare a general health to a diagnostics response containing many different values.

**Comment by marvinmarnold** [comment]
FYI @kashifpk the endpoints I'm implementing are `/v2/gen_add_gateway_txn` and `/v2/ack_add_gateway_txn`

**Comment by marvinmarnold** [comment]
Also I think a 406 HTTP error code should be returned if the DiagnosticsReport contains errors.

**Comment by kashifpk** [comment]
> Also I think a 406 HTTP error code should be returned if the DiagnosticsReport contains errors.

HTTP 406 Not Acceptable response usually means that data sent by the client is forcing the server not to be able to produce a valid response. Ideally we should return a 5xx error (in server errors range). In our case a 500 error with the diagnostics report json in response might be better?

**Comment by marvinmarnold** [comment]
In this case the error will most likely happen when the user tries to gen after an ack or acking twice. Seemed more like a client error then server to me. No strong opinion though.

**Comment by kashifpk** [comment]
Oh ok, in that case 406 makes much more sense. I was thinking about the GET requests getting this error as a response because they force ready only operations. Like for `/initFile.txt` endpoint. For the new endpoints I agree using 406 makes more sense if the cases you've mentioned.

**Comment by kashifpk** [comment]
@marvinmarnold - For verifying singed POST payload the most widely used option seems to [python-gnupg](https://github.com/vsajip/python-gnupg/) ([pypi](https://pypi.org/project/python-gnupg/)). Only drawback it has is that still uses the `gpg` binary via `subprocess` module.

There is a pure python implementation [python-pgp](https://github.com/mitchellrj/python-pgp) but it doesn't seem to be actively maintained.

If using the gpg binary via subprocess is acceptable then we can do it directly without using any library as we're only going to a single command.

Thought I'd put my thoughts in here for reference.

**Comment by marvinmarnold** [comment]
Thanks @kashifpk, I haven't done any research yet. Based on your findings, I'd go with python-gnupg. The project is actively maintained and it is likely we will do more PGP stuff down the road. I don't mind adding the dependency in that case.

**Comment by vpetersson** [comment]
I'm usually against shelling out with `subprocess` but in this case, it might be the best choice as it's very trusted component.

**Comment by kashifpk** [comment]
@marvinmarnold - how do you want to accept the full file content of the vendor specific signed data in `POST /v2/gen_add_gateway_txn`? I can send the whole content as raw post data, another approach would be to still send it as json with the whole file content either based64-encoded or urlquoted inside. 

If you have sketched out some expected format can you share that so I can send data from HPT in that format?

**Comment by marvinmarnold** [comment]
@pritamghanghas @MuratUrsavas yall should be ready to help get this over the line as @posterzh is likely going to be busy with app stuff for a few days. The PR https://github.com/NebraLtd/hm-diag/pull/298 is just about ready so it should just be a matter of merging and testing.

**Comment by MuratUrsavas** [comment]
@marvinmarnold :+1: 

@pritamghanghas Let's discuss this on Monday before the stand-up and decide what to do regarding to the issues we track currently.

**Comment by marvinmarnold** [comment]
@kashifpk please make a final review so this can be merged

**Comment by kashifpk** [comment]
@MuratUrsavas - ping. This one can be closed now.
