### ISSUE TITLE
Spike: Research EG25-G and recommend firmware update mechanism

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#285]
See: https://github.com/NebraLtd/hm-diag/issues/133

**Comment by shawaj** [comment]
We have a contact at Quectel if you need tony.forrester@quectel.com

**Comment by marvinmarnold** [comment]
@vpetersson can you identify devices in testnet with these chips

**Comment by shawaj** [comment]
@marvinmarnold they should have a tag saying cellular: eg25g I think so have a look for that

**Comment by pritamghanghas** [comment]
@marvinmarnold stuck with balena access to the nebra organization. I need access to the module. Need to find out the exact current_fw_version as well as model number. That will have to be sent to quectel, then they will send us the new firmware and flashing tool.

**Comment by shawaj** [comment]
Might be useful https://docs.sixfab.com/page/att-3g-sunset-guide

**Comment by pritamghanghas** [comment]
I think we have reached a stage where there are no unknowns left. I was able to update the firmware on a testnet device. 
The plan is to do following tasks during hm-diag initialization:

Use dbus API to find the current firmware version. 
   shell equivalent: `mmcli -m 0 --command='AT+QGMR'`
if trim(current_fw_version()) != "EG25GGBR07A08M2G_30.006.30.006" : 
     use dbus API to stop ModemManager.
         shell equivalent: `dbus-send --system --print-reply --dest=org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StopUnit  string:"ModemManager.service" string:"replace"`
     launch a process to upgrade firmware. both the too land firmware directory will be prepackaged in the docker image
        `"./QFirehose -f /var/data/EG25GGBR07A08M2G_30.006.30.006"`
     use dbus API to start ModemManager
         shell equivalent: `dbus-send --system --print-reply --dest=org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.StartUnit  string:"ModemManager.service" string:"replace"`
set user setting to "data centric". In new firmware it should be factory default but not taking any chances.
    shell equivalent: `mmcli -m 0 --command='AT+QNVFW="/nv/item_files/modem/mmode/ue_usage_setting",01'`
set service domain to PS. Have asked quectel if this is necessary but some guides mention it.
    shell equivalent: `mmcli -m 0 --command='AT+QCFG=“servicedomain”,1,1'`
Reboot the modem:
    shell equivalent: mmcli -m 0 --command='AT+CFUN=1,1'

we can check values before setting the values eg.
`mmcli -m 0 --command='AT+QNVFR="/nv/item_files/modem/mmode/ue_usage_setting"'`

* we will call all of dbus api from python without using mmcli or dbus-send.

**Comment by pritamghanghas** [comment]
I think there will be a small risk of bricking the module if device reboots in those 45s when upgrade is going on. 
Do we have a way to inhibit reboot in balena?
I found container update lock [here](https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/#application-update-locks) but didn't see any such lock for device reboot yet.

**Comment by pritamghanghas** [comment]
The recommendation from Quectel about service domain is this:

```
The service domain configuration AT+QCFG="servicedomain",1 will make the module attach to PS only. If your product doesn't need the SMS or voice, this configuration can be set. 

The reason for the suggestion to this command could be probably from the SIM operator, like AT&T, especially in the roaming environment. Some SIM doesn't save the CS_PLMN and as a result, after rebooting/CFUN 0&1/power on, it will take longer time than usual for the registration. Because the module has to search all the PLMNs to do the registration.

My suggestion is that 1) using the latest firmware and 2) consultant AT&T (or your SIM operator) whether you need this service domain configuration. 
```
I think it will be better and safer to set Packed switched mode in service domain.

**Comment by pritamghanghas** [comment]
This ticket is now complete. i am working on writing code for this.
