### ISSUE TITLE
Miner block height is higher than actual block number on hm-diag

### ISSUE THREAD

**Issue by ko2sec** [NebraLtd/hm-diag#286]
Not sure if this is related to hm-diag but sometimes miner block height is higher than actual block number of Helium.

![image](https://user-images.githubusercontent.com/38421562/150113944-6d89f5ec-493f-44a7-b7d0-fa70a3601e2f.png)

**Comment by vpetersson** [comment]
Interesting. We read this directly from the miner software so might actually be a bug there.

**Comment by ko2sec** [comment]
In that case I'm opening this issue to [helium-miner-software](https://github.com/NebraLtd/helium-miner-software) as well.

**Comment by vpetersson** [comment]
No, upstream Helium Miner, not ours.

**Comment by shawaj** [comment]
This is a known issue. It's because the API lags behind the local miner data

In reality it's not an issue at all.

**Comment by shawaj** [comment]
@vpetersson the only thing we could do is read the blockchain height directly from the miner as well, rather than from the API?

**Comment by shawaj** [comment]
We can close this now as no longer is syncing
