### ISSUE TITLE
Add Nebra software version

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#290]
We need to add this to diagnostics once implemented...

https://github.com/NebraLtd/hm-miner/issues/47

**Comment by marvinmarnold** [comment]
FYI, seems related to this: https://engineering.helium.com/2022/01/24/firmware-release-containerized-miner.html. Haven't dug into it much but we should be able to change the miner version independently of our firmware.

**Comment by shawaj** [comment]
Do we want to auto update the miner aromatically though? We have had various incidences of breaking changes not properly reported etc so not sure if maybe it's better not to?

**Comment by vpetersson** [comment]
I'm not in favor of auto updating. There has been way too many breaking changes in the past. Now that we will be doing various things over RPC etc, we need predictable behavior.

**Comment by marvinmarnold** [comment]
Agreed, not in favor of auto-updating. Just meant that there's an established pattern for updating miner independently of firmware.

**Comment by MuratUrsavas** [comment]
> Probably enough to do it in `/version` as I think HPT is pulling that anyways. Please confirm @kashifpk

I had been already added the information where the FIRMWARE_VERSION is reported. The PR's are ready.

https://github.com/NebraLtd/helium-miner-software/pull/350
https://github.com/NebraLtd/hm-diag/pull/291

The tests are OK thanks to @ilyastrodubtsev.

If you can approve them, we can close this ticket and follow-up the rest in https://github.com/NebraLtd/helium-miner-software/issues/351.

**Comment by MuratUrsavas** [comment]
Asking for the next sprint: We don't think using semantic auto versioning is better than what we have (date based versions) right now, hm-miner would get updated manually to fetch upstream changes and the release procedure would be kept as usual.

Am I correct?

**Comment by MuratUrsavas** [comment]
@vpetersson & @marvinmarnold Should we close this issue with the merge of NebraLtd/helium-miner-software#350 and then discuss the new version style in NebraLtd/helium-miner-software#351?
