### ISSUE TITLE
Proposal: Showing height status as diff, not fraction of ints

### ISSUE THREAD

**Issue by MuratUrsavas** [NebraLtd/hm-diag#301]
While trying to follow the blockchain status of the test device I had trouble comparing the API height and current device blockchain height (now in millions). You need to consider at least 4 or 5 digits to compare properly. The sync level doesn't help either. It generally shows as 100% but the device could be behind more than 20+ blocks.

So it would be better to show blockchain status as diff like this:
```
Height Status     +1 (1234431)
```
`+1` is the diff, (device block height - API block height) and the value in parenthesis is the API height. This way we can easily spot failing devices with a glance without doing some arithmetic.

A problematic height status would be shown like this:
```
Height Status     -56 (1234431)
```
Plus, we should also add three or 4 decimals to the sync level to make it meaningful for problem tracing. But in millions level, we would need at least 6 decimals. That could be a little bit of a problem, though.

This issue is also a complementary feature for #286

**Comment by shawaj** [comment]
Closing this as there is no longer sync
