### ISSUE TITLE
Light miner: Diagnostics page should display ECC detection

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#319]
- Related to: https://github.com/nebraltd/light-hotspot-software/issues/43
- Will the same gateway_mfr binary work for Pi Zero and other miners?

**Acceptance criteria**
- Miner container must be using hm-gatewayrs
- `ECC detected` shows correct state

**Comment by pritamghanghas** [comment]
There is no breakage here. It is already working with light-hotspot branches.
