### ISSUE TITLE
Helium address not wrapping well on mobile

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#32]
The new Helium address isn't wrapping correctly on mobile

![Screenshot_20210524-044811_Gallery](https://user-images.githubusercontent.com/3359418/119293917-46b88900-bc4b-11eb-9874-7641d35f641e.jpg)

**Comment by ryanteck** [comment]
Hmm yep seems like it does.

I'll tweak it the best I can and push it in a fix.

**Comment by ryanteck** [comment]
Fixed this

![Screenshot_2021-05-24-15-13-31-41](https://user-images.githubusercontent.com/1104745/119361572-b8bcbc80-bca3-11eb-9b44-b099d2459651.jpg)
