### ISSUE TITLE
Light miner: Region detection and support

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#320]
Originally: https://github.com/nebraltd/light-hotspot-software/issues/42
Relevant code: https://github.com/NebraLtd/hm-miner/blob/master/gen-region.sh

**Acceptance criteria**
- Miner container must be using hm-gatewayrs
- On Diagnostics page, `Region plan` displays correctly for onboarded and not-onboarded hotspots.
- Packet forwarder should not start unless a region is selected

**Comment by pritamghanghas** [comment]
Closed by merge of #321
