### ISSUE TITLE
QR code / web onboarding

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#33]
Look into implementing QR code onboarding using the diagnostics page

https://github.com/helium/hotspot-app/issues/498

**Comment by ryanteck** [comment]
Hmm this is a bit of a mixed one?

It seems it's in extreme early stages so isn't even supported in the app
yet.

But primarily it's used as an alternative when Bluetooth is not available?
So I'm a bit confused on why it's needed.

**Comment by shawaj** [comment]
https://helium-onboarding.kerlink.com/?wallet=14rsmPZPWPhhf6WczUCjktCpD2j1aajoSNpGobHkkwD61NP8NSg

![Screenshot_20210716-233101_Google Play Store](https://user-images.githubusercontent.com/3359418/126014693-81139549-b285-4fbf-81cf-a7dd74773079.jpg)
![Screenshot_20210716-233327_Helium](https://user-images.githubusercontent.com/3359418/126014696-6e0d9618-a77a-48cc-b12d-337cfa7efaf9.jpg)

**Comment by shawaj** [comment]
![Screenshot_20210716-233757_Helium](https://user-images.githubusercontent.com/3359418/126014867-eee367ca-7cb1-45a9-a9c6-83f2d3b5efbb.jpg)

**Comment by shawaj** [comment]
https://github.com/helium/hotspot-app/pull/783

**Comment by shawaj** [comment]
https://github.com/helium/hotspot-app/pull/731

**Comment by shawaj** [comment]
https://github.com/helium/hotspot-app/pull/617

**Comment by shawaj** [comment]
@vpetersson @JohnWhiting FYI

**Comment by vpetersson** [comment]
ping @robputt
