### ISSUE TITLE
Introduce a "network watchdog"

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#343]
It is expected that WiFi devices periodically drop off the network. I believe that Network Manager (NM) has some built-in mechanisms for recovering. However, there is a lot of room for improvement. 

I suggest that we introduce our own 'network watchdog' to rectify this. The logic would look something like the following:

* In a scheduled task, perform a check every hour (with jitter) if the device is able to connect to the internet (tbd how this check looks like)
* If the check is successful, just break, but if the check fails, add it to a counter (which is reset on success)'
* When the counter reaches X, perform a NM network restart
* When the counter reaches Y, perform a full system reboot

X and Y needs to be set diligently, as we don't want to do more than one reboot per 24 hour cycle (or similar). As such, we probably also need to keep an entry somewhere to prevent to frequent reboots.

**Acceptance criteria**
* In a scheduled task, perform a check every hour (with jitter) if the device is able to connect to the internet
* Check internet by: ping local gateway, ping 8.8.8.8, then curl google
*  If the check is successful, just break, but if the check fails, add it to a counter (which is reset on success)'
* When the counter reaches X, perform a NM network restart
* ~When the counter reaches Y, reboot service~
* When the counter reaches Y, perform a full system reboot
* Full system reboot limited to once a day
* Counter written to file 
* Include information in diagnostics upload to GCS:

**Comment by KevinWassermann94** [comment]
Awesome!

**Comment by Ryan-Goldstein** [comment]
Excellent idea! For my hosts who are connected with Wi-Fi, I often need to power cycle them with a smart plug or ask the host to power cycle them to get them back online.

**Comment by shawaj** [comment]
Yeah maybe a 24 hour reboot isn't a bad idea in general, like on all hotspots. Or even once a week or something. Clear out the cobwebs

**Comment by shawaj** [comment]
Would be nice to tie this in with the dashboard and/or app to give more up to date online/offline notifications

**Comment by posterzh** [comment]
@vpetersson Could you share some idea about the possible and best ways to persist the counters in the miner?

**Comment by posterzh** [comment]
Using `nmcli` cli command or dbus, it is possible to get the network connectivity state as follows(https://developer-old.gnome.org/NetworkManager/stable/nmcli.html):
- state-connected-local      | Indication that NetworkManager in local network.
- state-connected-site        | Indication that NetworkManager in connected to networks other than Internet.
- state-connecting              | Indication that NetworkManager is establishing a network connection.
- state-disconnected          | Indication that NetworkManager is disconnected from a network.

I want to carry out the tests how well this reflects the network connectivity in contrast with `ping` and `curl` command.
