### ISSUE TITLE
Fix diagnostics upload

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#353]
Possibly related to: https://github.com/NebraLtd/hm-diag/pull/271/files
See: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1652117473876719

**Acceptance Criterion**
- Diag is successfully ingested in bigquery.
- firmware_short_hash is added to bigquery.

**Comment by ilyastrodubtsev** [comment]
I researched the problem a bit. And it looks like we're still sending diagnostic data to bigquery.
But the data itself has undergone some changes. And we just can't insert them into our table in Biqguery.
For example: We expect boolean on bigquery side.
But diag sent string.

We lose over 20,000 diagnostic data every hour.

I've aggregated all the unique bugs we encounter.

```
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'ok', 'debugInfo': '', 'message': 'Field value of ok cannot be empty.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'KEY_STORAGE_BUS', 'debugInfo': '', 'message': 'no such field: KEY_STORAGE_BUS.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'IC_IDS', 'debugInfo': '', 'message': 'no such field: IC_IDS.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'GPIO_PIN_BUTTON', 'debugInfo': '', 'message': 'no such field: GPIO_PIN_BUTTON.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'FCC_IDS', 'debugInfo': '', 'message': 'no such field: FCC_IDS.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'CONTAINS_FCC_IDS', 'debugInfo': '', 'message': 'no such field: CONTAINS_FCC_IDS.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'mc', 'debugInfo': '', 'message': 'Cannot convert string value to boolean: Failed to Fetch'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'GPIO_PIN_LED', 'debugInfo': '', 'message': 'no such field: GPIO_PIN_LED.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'mr', 'debugInfo': '', 'message': 'Cannot convert string value to boolean: Failed to Fetch'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'pk', 'debugInfo': '', 'message': 'Field value of pk cannot be empty.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'fr', 'debugInfo': '', 'message': 'Field value of fr cannot be empty.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'an', 'debugInfo': '', 'message': 'Field value of an cannot be empty.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'md', 'debugInfo': '', 'message': 'Cannot convert string value to boolean: Failed to Fetch'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'firmware_short_hash', 'debugInfo': '', 'message': 'no such field: firmware_short_hash.'}]}]
ERROR:root:Error inserting data to BigQuery - [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'CONTAINS_IC_IDS', 'debugInfo': '', 'message': 'no such field: CONTAINS_IC_IDS.'}]}]
```

**Comment by kashifpk** [comment]
Nice research @ilyastrodubtsev - On a side note, looking at the error messages it looks like google/bigquery is also using pydantic for data validation @metawake  as these error messages seem very similar to what pydantic generates.

**Comment by pritamghanghas** [comment]
checked devices in testnet for rockpi and rpi fleets and diagnostics is shipping every hour consistently except for devices where following exception occors in that case perform_hardware_diagnostics() never finishes and thus no shipping.  this is a separate issue and we already have a ticket.

> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics] INFO:root:Running periodic hardware diagnostics
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics] 2022-05-25 03:30:43,170 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_mac_address -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(212) - Failed to find MinerMac Address file at path /sys/class/net/wlan0/address
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics] Traceback (most recent call last):
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics]   File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 208, in get_mac_address
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics]     file = open(path)
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics] FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/net/wlan0/address'
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics] ERROR:hm_pyhelper.miner_param:Failed to find MinerMac Address file at path /sys/class/net/wlan0/address
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics] Traceback (most recent call last):
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics]   File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 208, in get_mac_address
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics]     file = open(path)
> [Logs]    [5/25/2022, 9:00:43 AM] [diagnostics] FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/net/wlan0/address'

**Comment by pritamghanghas** [comment]
Just checked, it got shipped to production as well with yesterday's [GA 2022.05.24.0](https://github.com/NebraLtd/helium-miner-software/pull/458) release and diagnostics are shipping
