### ISSUE TITLE
fix: hm-diag python test workflow is failing due to a deb package missing

### ISSUE THREAD

**Issue by pritamghanghas** [NebraLtd/hm-diag#354]
The python tests workflow is failing because the version of libdus that apt tries to fetch is no longer there. Probably some critical fix has been published and older package removed. A simple apt udpate should fix it.

Log trail from workflow run:
> Run sudo apt-get install libdbus-1-dev libdbus-glib-1-dev python3-dev
> Reading package lists...
> Building dependency tree...
> Reading state information...
> python3-dev is already the newest version (3.8.2-0ubuntu2).
> The following NEW packages will be installed:
>   libdbus-1-dev libdbus-glib-1-dev libdbus-glib-1-dev-bin
> 0 upgraded, 3 newly installed, 0 to remove and 18 not upgraded.
> Need to get 276 kB of archives.
> After this operation, 1541 kB of additional disk space will be used.
> Ign:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libdbus-1-dev amd64 1.12.16-2ubuntu2.1
> Get:2 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libdbus-glib-1-dev-bin amd64 0.110-5fakssync1 [39.5 kB]
> Get:3 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libdbus-glib-1-dev amd64 0.110-5fakssync1 [69.2 kB]
> Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libdbus-1-dev amd64 1.12.16-2ubuntu2.1
>   404  Not Found [IP: 52.147.219.192 80]
> Fetched 109 kB in 0s (639 kB/s)
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/d/dbus/libdbus-1-dev_1.12.16-2ubuntu2.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> Error: Process completed with exit code 100.
>

**Comment by vpetersson** [comment]
This is most likely a temporary fluke. Unless we've bumped Debian version, packages don't disappear like this.
