### ISSUE TITLE
Add QR Code for onboarding the device on the dashboard

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#371]
In addition to NebraLtd/hm-dashboard#97 we should add a QR code to the diagnostics page to onboard the device in the dashboard.
The QR code should be displayable by hovering a tooltip promoting the dashboard

**Comment by shawaj** [comment]
Related to https://github.com/NebraLtd/hm-dashboard/issues/800

**Comment by shawaj** [comment]
Could also add a deep link perhaps

**Comment by vpetersson** [comment]
This needs to be scoped out in the next grooming.
