### ISSUE TITLE
Root cause analysis of faulty wifi on outdoor units

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#378]
Related to: https://github.com/NebraLtd/Hotspot-Production-Tool/issues/177

**Comment by pritamghanghas** [comment]
lsusb output: Enumerated with device model according to the id found at [http://www.linux-usb.org/usb.ids](http://www.linux-usb.org/usb.ids)
Bus 001 Device 009: ID 0a12:0001 - Cambridge Silicon Radio, Ltd - **(0001  Bluetooth Dongle (HCI mode))**
Bus 001 Device 004: ID 1a40:0101 - Terminus Technology Inc. - **(0101  Hub)**
Bus 001 Device 008: ID 04e2:1200 - 04e2  Exar  **(1410  XR21V1410 USB-UART IC (these guys are only have this id listed with Linux foundation)**
Bus 001 Device 006: ID 04e2:1100  **(exar doesn't have this id reported as well, same for the next two)**
Bus 001 Device 005: ID 04e2:1300  USB 2.0 Hub
Bus 001 Device 003: ID 04e2:0800  USB 2.0 Hub
Bus 001 Device 002: ID 1a40:0101  USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 - 1d6b  Linux Foundation
	0001  1.1 root hub
	0002  2.0 root hub

**Comment by pritamghanghas** [comment]
the devices that have the 802.11n usb dongles should have following line in `lsusb`:
`Bus 001 Device 007: ID 0bda:8179  USB 2.0 Hub `
if one checks the complete output with `lsusb -v` the kernel identifies it as 
```
iManufacturer           1 Realtek
iProduct                2 802.11n NIC
```
A simple test on the console for checking whether the dongle is attached or not:
`lsusb | grep 8179`
should result in following output.
`Bus 001 Device 007: ID 0bda:8179  USB 2.0 Hub`
if grep doesn't find anything, we have a missing dongle.

**Comment by pritamghanghas** [comment]
My conclusion is these faulty devices are either missing the dongle or the connection to the dongle is broken.

**Comment by pritamghanghas** [comment]
moving it to on hold, we will look at it when we get our hands on the faulty devices.

**Comment by marvinmarnold** [comment]
Waiting for device to reach UK office

**Comment by pritamghanghas** [comment]
@KevinWassermann94 Did we receive any of these miners?

**Comment by marvinmarnold** [comment]
@KevinWassermann94 any update?

**Comment by KevinWassermann94** [comment]
This specific device had a loose USB daughterboard. I'll try to gather more data on the others ones together with Wayne
