### ISSUE TITLE
Spike: Follow up on IPv6 and general support for T-Mobile with Quectel

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#379]

**Comment by pritamghanghas** [comment]
@marvinmarnold News reports show T-Mobile 3G shutdown by 31st May. Shall I remove the check for AT&T and proceed with a release. Most of the articles mention that it was supposed to be phased, may already be in progress.

**Comment by pritamghanghas** [comment]
@marvinmarnold Quectel now recommends choosing non-default APN. But I think they have suggested this keeping in mind our T-Mobile problem. I can try this if I can get ipv4 as well for T-Mobile on new firmware.  Will need a device though with T-mobile sim. I had asked them if there is a generic solution possible at global level that we can deploy to always get ipv4, they keep suggested APN tricks.

**Comment by marvinmarnold** [comment]
@pritamghanghas this miner is setup for you to use: https://dashboard.balena-cloud.com/devices/fd5f350f18f50c45a1a23eeb1a3170da/summary

**Comment by pritamghanghas** [comment]
Tried to look for a configuration option in NetworkManager because android seem to allow selection of protocol ipv4, ipv6, ipv4/ipv6 but didn't find such an option for NM.

**Comment by pritamghanghas** [comment]
checked on both firmwares. The status is same. So it seems "our decision to do nothing on the firmware upgrade is good". 
the current firmware = {
    "EG25GGBR07A08M2G": "EG25GGBR07A08M2G_01.001.01.001",
    "EG25GGBR07A07M2G": "EG25GGBR07A07M2G_01.001.01.001",
}
seems to work fine and gets both ipv4 and v6 while newer firmware gets only ipv6.

**Comment by pritamghanghas** [comment]
Waiting for Quectel if they come up with some generic way of handling this with AT commands.

**Comment by pritamghanghas** [comment]
T-Mobile doesn't have a generic solution for this. Waiting for helium to be ipv6 ready seems to be only strategy right now. Nothing more to do here.
