### ISSUE TITLE
Miner height - add current total height of blockchain

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#38]
Would be useful to have the total current blockchain height and a percentage.

I.e.

12345/12345 (100%)

**Comment by ryanteck** [comment]
I didn't want to add this in to avoid 1000s of devices pulling the latest height from the blockchain every 5 minutes.

However if you think it will help I can add it in.

**Comment by ryanteck** [comment]
This is now added in and wil be in the 2021.06.01.0 software update releasing later today.

**Comment by shawaj** [comment]
> I didn't want to add this in to avoid 1000s of devices pulling the latest height from the blockchain every 5 minutes.

Do you mean to avoid slamming the Helium API with requests or something else?

**Comment by ryanteck** [comment]
Yes that is what I meant, however I have now added it in.
