### ISSUE TITLE
Remove freq from diagnostics

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#388]
Acceptance Criteria
- [ ] Create new diagnostics to read region from file and show frequency based off of that

**Comment by pritamghanghas** [comment]
@KevinWassermann94 Shall we totally remove this. I don't know what additional value it provides when "region" key is already there and it is displayed under "Region Plan" in diagnostic page. Seems redundant.

**Comment by KevinWassermann94** [comment]
Makes sense. The only difference is that the region plan will be unavailable when no location has been asserted yet.
@marvinmarnold What do you think?

**Comment by pritamghanghas** [comment]
@KevinWassermann94 Frequency will also be unavailable when unasserted. Our plan was is to deduce it from region and that is how miner decides it.

**Comment by KevinWassermann94** [comment]
You are right

**Comment by pritamghanghas** [comment]
blocked by https://github.com/NebraLtd/hotspot-production-images/issues/49
once frequency file injection is done.

**Comment by marvinmarnold** [comment]
@NebraLtd/device-team can we remove this from the sprint? I don't think we want to do this yet.

**Comment by marvinmarnold** [comment]
@NebraLtd/device-team this has been removed from the sprint
