### ISSUE TITLE
Password protect?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#39]
Like with WiFi routers I think we should password protect this page. Had a few people exposing it to the internet and being surprised to know that it's got sensitive info on it.

We can password protect perhaps with the last 6 digits of Mac address or RasPi serial.

And we could allow people to change the password but with a factory reset option to put it back to the default.

**Comment by ryanteck** [comment]
Well kinda the idea is that it is a dumb page.

If we start adding in password protection then it is no longer a dumb page and requires quite a bit adding to it.

Furthermore then it could require changes for production, as the production steps rely on accessing this data.

**Comment by vpetersson** [comment]
Blocked by #60.

**Comment by robputt** [comment]
Reopening this issue as discussed with @shawaj

**Comment by shawaj** [comment]
#441 fixes this. Will close this issue once in testnet and verified by tech support
