### ISSUE TITLE
Send to support functionality?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#40]
Perhaps a button we can get people to press that downloads a txt file with diagnostics info to send us.

Similar to what's in the app

**Comment by ryanteck** [comment]
Yeah this would be quite good to add in, all of the data is already stored in a json file so it can just be we have a download link to download that.

**Comment by ryanteck** [comment]
I've added a link to the bottom of the page so it can download the JSON file produced by the diagnostics software.

This downloads into a file with timestamp each time.

![Screenshot from 2021-06-01 13-43-39](https://user-images.githubusercontent.com/1104745/120325229-613fd180-c2df-11eb-992d-fb6a7c0fc3f1.png)
