### ISSUE TITLE
Add more features / match with dashboard

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#41]
I think it would be nice if the remote dashboard and the local dashboard converge to have similar features from a device info / device control perspective...

Things we could add:
- reboot, shutdown, restart
- relayed status
- network statistics 
- Eth / WiFi status
- WiFi network search and update
- mDNS / NetBIOS search (nebra.local or macaddress.local or similar)
- local / wan IP displayed for all interfaces
- explore miner features
  - peer book
  - connect to new peers
  - take snapshot
  - restore snapshot
- Customisable lora RF settings (rssi offset / antenna gain / tx power)

Probably a bunch more we could add, just wanted to get the conversation started 👌

**Comment by ryanteck** [comment]
I mean kinda the idea of the diagnostics system is that it is for diagnostics and picking up on issues.

Adding all of the above then turns it more from a diagnostics system to a management panel. So is most likely an entire re-write of the system.

**Comment by whittinghamj** [comment]
I really like these ideas.

Habing a local dashboard on the hotspot itself would be a massive help - maybe even have a little JSON API endpoing for the techie's to tap into as well.

I would ask that the API endpoint has a reboot option as well?

**Comment by vpetersson** [comment]
Blocked by #39. However, once done, we should be able to knock most of these out fairly easily.

**Comment by shawaj** [comment]
Some inspiration

https://medium.com/@syncrob_it/local-dashboard-customize-everything-5a57b129b112

**Comment by shawaj** [comment]
![image](https://user-images.githubusercontent.com/3359418/122654410-1af1cb80-d143-11eb-8321-4091c9e5a70f.png)

**Comment by shawaj** [comment]
Turns out balenaOS already has mDNS / NetBIOS enabled on `<shortuuid>.local` but we can modify this using the supervisor api

https://www.balena.io/docs/reference/supervisor/supervisor-api/#patch-v1devicehost-config

I'm thinking `nebra-<last 6 digits of Mac address>. local`

**Comment by bjessie** [comment]
Could temperature be added to the local diagnostics page without much fuss? The metric is already available in the remote dashboard. I've had great difficulty keeping them cool and this would be incredibly helpful.

**Comment by smurf12345** [comment]
I would like to second the request for temperature to be added to the local diagnostics.  I pull the json with a script to monitor my hotspot and the dashboard doesn't seem to have it's own API from what I can find (I could be wrong).  Also as I understand, the dashboard will be not be free in the future based on the login message.   Dashboard message: "Heads up!
We just wanted to inform you that this dashboard will be a paid product soon." 
Thanks for all the continuing hard work on this miner software!

**Comment by shawaj** [comment]
We are working on some new features that should make this much easier.

A lot of the information on the dashboard comes from the balena API (we use balena to manage updates etc) which means it's inbuilt to the balenaEngine / balena supervisor setup. 

We are soon going to have a "watchdog" which will enable a bunch of these features.

Re the API - the dashboard does have one but it's not exposed externally or documented yet.
