### ISSUE TITLE
Messaging for disabled blockchain sync

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#411]
We need to add a banner to the diagnostics page to explain the changes to blockchain sync

**Comment by Louisreed** [comment]
`            <div class="alert alert-primary alert-dismissible fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                <h2 class="alert-heading">What happened to sync percentage?</h2>
                <p>Helium has converted all existing hotspots into <a href="https://blog.helium.com/light-hotspots-explained-everything-you-need-to-know-f86612f571c6" target="_blank">light hotspots</a>. Sync percentage and other blockchain features are now handled by validators, not hotspots. We appreciate your patience with any issues during the transition period.</p>
                <a href="https://blog.helium.com/light-hotspots-explained-everything-you-need-to-know-f86612f571c6" target="_blank" class="btn btn-light">More Information</a>
            </div>
`

**Comment by Louisreed** [comment]
```
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <h2 class="alert-heading">What happened to sync percentage?</h2>
    <p>Helium has converted all existing hotspots into <a
            href="https://blog.helium.com/light-hotspots-explained-everything-you-need-to-know-f86612f571c6"
            target="_blank">light hotspots</a>. Sync percentage and other blockchain features are now handled by
        validators, not hotspots. We appreciate your patience with any issues during the transition period.</p>
    <a href="https://blog.helium.com/light-hotspots-explained-everything-you-need-to-know-f86612f571c6" target="_blank"
        class="btn btn-light">More Information</a>
</div>
```
