### ISSUE TITLE
Sync % error?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#44]
![Screenshot_20210601-183813_Chrome](https://user-images.githubusercontent.com/3359418/120383329-a7675600-c31c-11eb-941f-93148999400b.jpg)

https://discord.com/channels/404106811252408320/796070988118360094/849348615344226324

**Comment by ryanteck** [comment]
I'll tweak the code, I believe I have the rounding a bit too tight so it's rounding to 100%.
