### ISSUE TITLE
Fix authentication for miners with no ethernet

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#449]
A couple of miners (Finestra for example) do not have ethernet.

In that case, we should use the WiFi Mac address

https://github.com/NebraLtd/hm-diag/blob/4a9cdafd8d1867d1b7bd16f0a4deaf7f94215ce5/hw_diag/utilities/auth.py#L57-L61

Or perhaps we use the `MAC` key from hardware definitions as the default:
https://github.com/NebraLtd/hm-pyhelper/blob/8fa184c6026c5f9009fc61ea583883679fed5057/hm_pyhelper/hardware_definitions.py#L54

And if there is not one then fall back to eth, and if not eth then fall back to WiFi.

What do you think @robputt ?

**Comment by pritamghanghas** [comment]
@shawaj There is another issue with the mac address as password. Our thermal labels fade away overtime. In such a case, the user has to find his mac from his internet router. Assuming he knows how and where to look for mac of connected devices.

**Comment by shawaj** [comment]
@pritamghanghas I think finding it from router is probably an acceptable amount of effort. We also include 2 additional spare serial number stickers in the box with the miner, as well as the one attached to the miner itself. Also our tech support can probably help people get it as well.

I'm but sure what other default we could use though? And we need the auth to enable other features.

@KevinWassermann94 @NebraLtd/developers any other thoughts on this?
