### ISSUE TITLE
Should we add password prompt or typing shutdown / reset for performing these actions?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#455]
@KevinWassermann94 what's your opinion on this? Should we make this more difficult or do you think it's ok as it is?

![Screenshot_20230115_225444_Chrome](https://user-images.githubusercontent.com/3359418/212572368-4e22b432-8c4e-4434-9a9a-272d7337cb2f.jpg)
![Screenshot_20230115_225448_Chrome](https://user-images.githubusercontent.com/3359418/212572369-7cacb3d0-4002-4372-be4a-c4970228dad6.jpg)

**Comment by robputt** [comment]
Getting the user to type in stuff is superfluous and annoying in my opinion. I hate control panels that make me do that, and I wish there was a way to opt out. This is not some data critical operation or life critical operation, the worse consequence is the user has to go restart their hotspot by hand if they screw up.

**Comment by KevinWassermann94** [comment]
@shawaj @robputt Agreed, this should be secure enough, considering that these actions are not that critical

**Comment by shawaj** [comment]
Lol. I quite like them @robputt as I have several times in the past hammed the keyboard or double clicked accidentally and done bad things.

But if you both don't think it's necessary then let's close 👌
