### ISSUE TITLE
Multiple local IP addresses (especially ipv6) causes formatting issues

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#467]
Multiple local IP addresses (especially ipv6) causes formatting issues...

![Screenshot_20230121_013902_Chrome](https://user-images.githubusercontent.com/3359418/213834347-aa8d4dcc-fccd-45ea-9c09-576874d40a57.jpg)

**Comment by shawaj** [comment]
This is still an issue by the way @robputt ...

![Screenshot_20230204_014425_Chrome](https://user-images.githubusercontent.com/3359418/216739946-4544738f-8630-4261-90d1-6b6d88c1a3f8.jpg)

**Comment by shawaj** [comment]
this is still happening on the new template on smaller screen sizes @robputt

**Comment by Louisreed** [comment]
Tables/cards need 'overflow-x: scroll'
