### ISSUE TITLE
Clarify timezone of "last updated" time

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#47]
At the bottom it has "last updated" time. We should clarify that this is UTC

**Comment by shawaj** [comment]
Maybe also worth having the date in a verbose format like 3rd June 2021 in case people get confused

**Comment by ryanteck** [comment]
Tweaked to add in UTC and a more universal date format.

![Screenshot from 2021-06-03 11-33-03](https://user-images.githubusercontent.com/1104745/120631166-780d3200-c45f-11eb-
8df4-0617bd1a00f7.png)
