### ISSUE TITLE
Difficult to read device metrics

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#479]
Impossible to read device metrics values...

<img width="1440" alt="Screenshot 2023-02-05 at 23 23 16" src="https://user-images.githubusercontent.com/3359418/216852924-1b6b17c5-e2ac-41f1-af40-63fe6f69074f.png">

**Comment by Ryan-Goldstein** [comment]
Was just about to submit an issue about this as well:

![image](https://user-images.githubusercontent.com/8300089/217056632-08b252a9-926d-4e48-8fec-f20e4dac87ea.png)

Loving the new UI, though! Really coming along well. Appreciate all the work being put into the firmware these days!

**Comment by shawaj** [comment]
Thank @robputt on that. 

And watch this space for some premium features like Mysterium dVPN etc

**Comment by Louisreed** [comment]
Device info should be displayed like this:

<img width="814" alt="Screenshot 2023-05-02 at 11 02 13" src="https://user-images.githubusercontent.com/9106988/235637890-beca3050-6c40-4ad7-af56-15f473d05f08.png">

**Comment by shawaj** [comment]
Looks ok.

TBH I preferred it in the actual graph bit but hard to do that and it be readable.

So yeah I think this is probably the best of both worlds.

**Comment by shawaj** [comment]
This is how it looks on balenaCloud for reference, very similar...

![Screenshot_20230502_170516_Chrome](https://user-images.githubusercontent.com/3359418/235722413-d2424b23-7083-436a-9c89-d34bbc1ee7cf.jpg)
