### ISSUE TITLE
When window is full size but small width the page length is unnecessarily long...

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#480]
<img width="1248" alt="Screenshot 2023-02-05 at 23 48 07" src="https://user-images.githubusercontent.com/3359418/216853065-b6d4ea29-53e0-4b1d-a9a4-6c77f8e7f582.png">
<img width="1137" alt="Screenshot 2023-02-05 at 23 47 54" src="https://user-images.githubusercontent.com/3359418/216853069-128b730c-749c-4835-968e-6018fc2612b0.png">
<img width="1139" alt="Screenshot 2023-02-05 at 23 48 40" src="https://user-images.githubusercontent.com/3359418/216853071-c395991d-2702-4eec-8a7d-77a81432f7c7.png">

**Comment by Louisreed** [comment]
Setting the background or container to 'height: 100%' should resolve this.
