### ISSUE TITLE
Use proc/cpuinfo for hardware serial

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#496]
Acceptance Criteria:
- Use `/proc/cpuinfo` for hardware serial mainly
- Use current path (`/proc/device-tree/serial-number`) as backup

**Comment by pritamghanghas** [comment]
this requies more work. if is there but all zero disregard that.

**Comment by shawaj** [comment]
Closing this in favour of #507 as the fix is in. Just needs better tests
