### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#51]
Was talking to Kevin and we had an idea that maybe we could add some error log view/download to the diagnostics to help with debugging, specifically the miner error log...

https://github.com/NebraLtd/hm-miner/issues/2#issuecomment-854195426

**Comment by ryanteck** [comment]
It'll be something I can have a little look into however I'm not fully sure
if error logs are stored to disk.

**Comment by shawaj** [comment]
they are stored at /var/log/miner/error.log

**Comment by ryanteck** [comment]
@shawaj I just needed to have 5 minutes to look into it myself. It's like 12AM which is why I said "I'm not fully sure" and I would have looked myself in the morning!

**Comment by shawaj** [comment]
@ryanteck not an issue, just thought it would save you a bit of time :-)

**Comment by robputt** [comment]
@shawaj @vpetersson is this still relevant or required?

**Comment by robputt** [comment]
> Maybe. Would perhaps be handy to have something that can be attached to support tickets. That said, we are working with Balena to see if we can get some kind of granular permission system in place (such that customers can grant access), which would kind of be an alternative solution to this.

Can we not use Balena API and wrap this in our own auth / permissions system within dashboard.nebra.com?

**Comment by vpetersson** [comment]
Yes, but all users won't be using the dashboard.

**Comment by shawaj** [comment]
@vpetersson what do you mean by customers can grant access? As in we would give people access directly to their devices on balena?

**Comment by vpetersson** [comment]
No, I was referring to what Joe from Balena was referring to. However, support can already pull logs from Balena so not sure how useful this feature is. The only scenario I can think of where it would be useful is if the device is offline, but accessible on a local network. For all other scenarios, it would be easier to just pull logs from Balena directly.

**Comment by icep87** [comment]
Is it possible for end user to pull logs from Balena for their own hotspot? 

It might be useful for the community/end user to access the logs so we can help each other out in solving those smaller issues. 

That will I guess generate less support tickets to the support team.

**Comment by wolasss** [comment]
+1. I have also syncrobit hotspots and they provide miner logs, which is **VERY** useful for debugging witnesses and p2p network fails. Being able to view the miner logs is absolutely a must IMO

**Comment by shawaj** [comment]
@icep87 @wolasss at the moment this is not possible and to be honest is something that very few customers want or need to use as most of them are not particularly technical.

Having said that, it is something we are looking into but it's not particularly high on the to do list.

You can subscribe to this issue to track progress with it though 👍

**Comment by wolasss** [comment]
> at the moment this is not possible and to be honest is something that very few customers want or need

Did you ask your customers though or this is just an assumption?

I am willing to contribute and dedicate my time to implement this if possible.

**Comment by MagNaMan** [comment]
I would love to see logs.  Please add to local diag page.

**Comment by shawaj** [comment]
> Did you ask your customers though or this is just an assumption?

It's not an assumption that the vast majority of people with hotspots wouldn't know what the logs mean, and that they are not particularly useful anyway as any pertinent information is already shown in the diagnostics page (and more will be added over time). 

As said, we have it on the list but it's not a very high priority right now. Additionally, there are some features that need to be implemented before logs can be introduced safely.

**Comment by icep87** [comment]
Great to know that you haven’t given up on the idea.

I agree that this would help a lot especially as I’m daily trying to help people out in the Discord channels with issues they have and understand a bit more about how it all works.

The logs would give more tools to let the community help each other out. Especially now when the respond time for tickets are so longs.

As example I’ve had a brand new hotspot that I’m unable to onboard as the Balena image does not seems to boot properly. It took over a week just to get an response and takes more than 24 hours to get an answer after responding.

Sent with a Spark
