### ISSUE TITLE
Percentage error on relayed device?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#52]
This is a device that had been online for some time (many days), but is stuck syncing. Shows really high percentage and that blockchain is only on block 1

<img width="1439" alt="Screenshot 2021-06-03 at 23 31 13" src="https://user-images.githubusercontent.com/3359418/120721867-9eb28380-c4c6-11eb-8f7c-2e17a3c27c37.png">

**Comment by shawaj** [comment]
relates to freshdesk ticket #244346

**Comment by ryanteck** [comment]
I don't really see the issue, it stays at 1 if it is unable to request it from the Helium API. 

Some value needs to be there, when it was 0 it caused errors due to dividing by zero to get the percentage.

I can add a cap to the percentage maybe. But otherwise it's working as intended.

**Comment by shawaj** [comment]
IMO it would be better to have it say something like an error message instead of 1. Something like "Waiting for block from Helium" or similar so that it is obvious.

And to just show a similar error message in the percentage.

Otherwise it just looks like a bug to someone that doesn't know

**Comment by ryanteck** [comment]
I've added a test in so if it is < 1% (Either just setup or powered on) that it will show as miner is still loading.

The same for if the percentage is > 100%

![Screenshot from 2021-06-09 11-49-18](https://user-images.githubusercontent.com/1104745/121342038-2cec9680-c919-11eb-9810-f676d40e18df.png)
