### ISSUE TITLE
Fix diagnostics page for light miner

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#521]
I don't think this will work: https://github.com/NebraLtd/hm-diag/blob/d7844079b924daf171b5588b0142ff782c6ea599/hw_diag/templates/diagnostics_page_light_miner.html

As this is the new format:
https://github.com/NebraLtd/hm-diag/blob/d7844079b924daf171b5588b0142ff782c6ea599/hw_diag/templates/helium_info.html

**Comment by shawaj** [comment]
FYI @MuratUrsavas ^^

**Comment by MuratUrsavas** [comment]
@shawaj Should I remove that old residue, then?

**Comment by MuratUrsavas** [comment]
@shawaj It's stub now, we can easily remove that. Let's do this in next change. No need to deal with it for two PR's.

**Comment by shawaj** [comment]
ahh so this template diagnostics_page_light_miner.html is not being used? 

Also - it looks like diagnostics.RE in here is checking for UN123 - but I think we deprecated that functionality now? https://github.com/NebraLtd/hm-diag/blob/d7844079b924daf171b5588b0142ff782c6ea599/hw_diag/templates/helium_info.html#L60-L82

**Comment by shawaj** [comment]
@MuratUrsavas what will it show if the location is not asserted?

**Comment by shawaj** [comment]
We also need to add the connected validator bit:

https://github.com/NebraLtd/hm-diag/blob/d7844079b924daf171b5588b0142ff782c6ea599/hw_diag/templates/diagnostics_page_light_miner.html#L109-L116
