### ISSUE TITLE
add popup for multi-mining with mysterium

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#532]
add popup for multimining with mysterium dvpn

**Comment by shawaj** [comment]
Similar to 

https://github.com/NebraLtd/hm-diag/blob/5bc4892c690c5715a9ac3ac0b72be3269a238475/hw_diag/templates/diagnostics_page_light_miner.html#L21-L49

**Comment by shawaj** [comment]
CC @KevinWassermann94

**Comment by robputt** [comment]
What is the purpose of this pop up @KevinWassermann94 @shawaj ?

**Comment by KevinWassermann94** [comment]
@robputt The idea is to educate our users that we will now be supporting Myst for multi-mining

**Comment by shawaj** [comment]
yep exactly that - just to make it so that it shows more obviously on the main page (could even put a notice on login page if we wanted to) - rather than just a menu item.

we will remove it after a month or two...but just to push people towards playing with Myst, TTN, ThingsIX stuff...and by extension to dashboard subs

**Comment by shawaj** [comment]
Closed by #581
