### ISSUE TITLE
thingsix page layout issues

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#534]
address overhanfgs...

<img width="1418" alt="Screenshot 2023-04-13 at 14 35 59" src="https://user-images.githubusercontent.com/3359418/231778587-b4ea9e9c-1716-4aca-8a3e-ba4ecd8e113d.png">

**Comment by Louisreed** [comment]
Add 'overflow-x: scroll' to the Gateway Address value.

**Comment by shawaj** [comment]
Can you do a PR @Louisreed to fix all the layout issues?
