### ISSUE TITLE
mysterium page layout has footer even though it is an iframe

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#551]
see below...
<img width="1421" alt="Screenshot 2023-04-14 at 23 42 34" src="https://user-images.githubusercontent.com/3359418/232166632-3ab94d49-ee53-4733-88b7-85461c66fc6e.png">

**Comment by shawaj** [comment]
@robputt guess we can do something like...

```
.footer {
display: none;
}
```

but only on this page?

**Comment by shawaj** [comment]
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/3359418/232928394-7518549e-9ac1-499c-8963-a1c960321350.png">

also it is impossible to click the buttons that overhang into footer like above

**Comment by Louisreed** [comment]
@robputt If that doesn't work try playing around with the position and z-index.

**Comment by shawaj** [comment]
@Louisreed are you able to fix all these with a PR?
