### ISSUE TITLE
Pairing shows incorrect firmware version

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#56]
According to the local diagnostics the hotspot is running on hotspot verison 2021.06.10.0 but when pairing in the app it is still showing firmware version 2021.06.09.4

**Comment by ryanteck** [comment]
Should be fixed in 39c54b2eb0c412f4a84a3248019086c3a7fa2167

**Comment by shawaj** [comment]
@KevinWassermann94 can you confirm this is working for you now?

**Comment by shawaj** [comment]
@KevinWassermann94 did you manage to test this?

**Comment by shawaj** [comment]
Closing as no reply
