### ISSUE TITLE
ability for enabling offboard antenna on CM4 based miners (Syncrobit)

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#561]
CM4 has a dtparam called ant2 which enables an offboard antenna (instead of an onboard) on WiFi CM4s.

This is possible on Syncrobit miners to enable an offboard antenna by adding a dtparam of `dtparam=ant2`

https://www.jeffgeerling.com/blog/2022/enable-external-antenna-connector-on-raspberry-pi-compute-module-4

I think we can do this using the balena supervisor (or probably using device env variables) to enable the offboard antenna.

I do not think that can be done at runtime - as it is needed to be in the config.txt and parsed at boot.

**Comment by pritamghanghas** [comment]
this can be done using env var. config.txt vars begin with BALENA_HOST_CONFIG_
https://docs.balena.io/learn/manage/configuration/#adding-custom-configuration
We might need to ensure that we don't overwrite any exiting values.

**Comment by shawaj** [comment]
Yes just not sure if we can do that from the device supervisor?

**Comment by shawaj** [comment]
Closed by #567
