### ISSUE TITLE
disk usage doesn't show any useful information

### ISSUE THREAD

**Issue by ChristopherRush** [NebraLtd/hm-diag#564]
The disk usage doesn't show the total available space on the device or any unit of measurement.

![Screenshot 2023-05-01 at 18 21 06](https://user-images.githubusercontent.com/1878314/235495904-3f0834da-8122-477f-afb8-7ef94c25eb0a.png)

**Comment by shawaj** [comment]
Duplicate of #479 

The info is actually there, you just can't read it due to the layout
