### ISSUE TITLE
Ability to turn off UPnP?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#57]
We had a customer who says they were having issues when port forwarding on a ubiquiti router due to port forwarding and UPnP being active. Thought maybe it might be useful to have a setting in diagnostics to deactivate upnp on the miner.

**Comment by ryanteck** [comment]
Currently it wouldn't be possible as the diagnostics system isn't designed to allow any configuration.

However I have had a few reports of issues with UPnP not quite working, or that it doesn't always stay working so I'm thinking possibly for now that it could be better to disable it and recommend people manually PF?
