### ISSUE TITLE
Add multi-mining info to dashboard upgrade banner

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#573]
Add multi-mining info to dashboard upgrade banner

<img width="1417" alt="Screenshot 2023-05-11 at 22 40 44" src="https://github.com/NebraLtd/hm-diag/assets/3359418/e9f3dce8-bdda-45fd-a501-e3daffef6a6e">

Related to #532

**Comment by KevinWassermann94** [comment]
@Louisreed Was this part of your recent changes?

**Comment by shawaj** [comment]
Closed by #605
