### ISSUE TITLE
Remaining layout issues June

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#593]
Ip Addresses not obviously separated...

![Screenshot_20230605_004631_Chrome](https://github.com/NebraLtd/hm-diag/assets/3359418/f60200d9-1e12-4006-b7d6-f228afba3928)

Footer still missing on small screen / mobile...

![Screenshot_20230605_004228_Chrome](https://github.com/NebraLtd/hm-diag/assets/3359418/abe6fa7f-dbc9-4508-a8dd-b17ad11ac45f)

Side nav auto closes if you scroll down...

https://github.com/NebraLtd/hm-diag/assets/3359418/937a639d-0b5b-4856-9dae-7eb4653d80db

**Comment by shawaj** [comment]
Meta theme colour removed since hyper update...

**Comment by shawaj** [comment]
Large amount of empty space between content and footer on small screens...
![Screenshot_20230605_004631_Chrome](https://github.com/NebraLtd/hm-diag/assets/3359418/b95a7070-168e-45cf-a216-1ad7df50e578)
![Screenshot_20230605_004348_Chrome](https://github.com/NebraLtd/hm-diag/assets/3359418/0d4c784e-5e5f-4cff-ae4b-211b100c6f09)
![Screenshot_20230605_004246_Chrome](https://github.com/NebraLtd/hm-diag/assets/3359418/38e56d65-eeab-427a-ba66-409027a6ece5)

**Comment by shawaj** [comment]
@KevinWassermann94 @WayneNebra @robputt crack any layout issues you find in the new diagnostics in here for @Louisreed

**Comment by shawaj** [comment]
Should add dark theme as per #475

**Comment by shawaj** [comment]
helium serial spills over edge of container... 
<img width="1420" alt="image" src="https://github.com/NebraLtd/hm-diag/assets/3359418/84c59134-c960-4b2a-a436-b3775ff58980">

**Comment by shawaj** [comment]
We should also fix #573 as part of this too...
<img width="1420" alt="Screenshot 2023-06-07 at 18 11 38" src="https://github.com/NebraLtd/hm-diag/assets/3359418/2d108848-7034-42bb-8598-b55f8dd14f50">

**Comment by shawaj** [comment]
Also on upgrade page, the button is an odd colour and the whole thing is not responsive and does not fit smallish windows...
<img width="1423" alt="image" src="https://github.com/NebraLtd/hm-diag/assets/3359418/2ae267bb-62b5-4e36-b8ec-9d83431e1ab3">

**Comment by Louisreed** [comment]
IP addresses are being displayed through {{ device_info.ip_address }}, no available option to filter

**Comment by Louisreed** [comment]
Unable to reproduce 'Side nav auto closes if you scroll down' error. Will require further testing on more devices. @shawaj is this just with chrome on Android?

**Comment by WayneNebra** [comment]
Same for me on an Android Oppo. 

https://github.com/NebraLtd/hm-diag/assets/90446757/644149af-e8e4-4e38-bf77-08886bfad13b

**Comment by Louisreed** [comment]
> 

Strange! I'll have to try with other devices. I have an iPad so will test on there as well.

**Comment by shawaj** [comment]
Same issue in iPhone safari @Louisreed

**Comment by shawaj** [comment]
> IP addresses are being displayed through {{ device_info.ip_address }}, no available option to filter

@Louisreed can they be split out using JS or something? As presumably they have got spaces between them?

**Comment by Louisreed** [comment]
Issue resolved!

**Comment by Louisreed** [comment]
> > IP addresses are being displayed through {{ device_info.ip_address }}, no available option to filter
> 
> @Louisreed can they be split out using JS or something? As presumably they have got spaces between them?

Yeah I thought about using split() but would be better if I could directly access each IP. I'll see what I can do.

**Comment by shawaj** [comment]
@Louisreed ping @robputt on slack - he might know a better way to split these out in python and then just pull them in as an array or list or whatever

**Comment by shawaj** [comment]
Closed by #608 #615 #616
