### ISSUE TITLE
Rewrite service to use Flask

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#60]
Let's rewrite the diagnostics page to use [Flask](https://flask.palletsprojects.com/en/2.0.x/), which gives us a lot of free features out of the box. We should then serve this app using [Gunicorn](https://gunicorn.org/).

To keep things simple, let's ditch the Nginx container for the time being and serve Gunicorn on port 8000 with Docker exposing it on port 80. That way we don't need to run the container as root.

This is a per-requisite for #39.

**Comment by ryanteck** [comment]
@vpetersson Primarily the reason the container is run as root is to access many of the hardware and networking services. Not for Nginx.

**Comment by robputt** [comment]
@vpetersson I'd quite like to claim this one, after looking at the code base + tests in the outstanding PR the conversion should be relatively straight forward.

**Comment by shawaj** [comment]
Closed by #92
