### ISSUE TITLE
icons and other assets don't load if no working internet connection

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#603]
As it's possible that there might be times when internet is not guaranteed (i.e. it's like a router rather than a public website) we need to store all icons, css, js, logos, images for the diagnostics locally rather than grabbing them over the internet.

So we will need to store them all locally rather than serving from cloudflare, font awesome etc

Foot example we currently are grabbing some stuff from remote sources:

https://github.com/NebraLtd/hm-diag/blob/5705da57ed8d8f3bc41edfe1c15fcdd18e55ee0f/hw_diag/templates/template_hyper.html#L14-L15

We need to remove all of these and serve locally.

Ref https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1686232425142909?thread_ts=1686164871.136669&cid=C024BNQ1Y6T

**Comment by Louisreed** [comment]
Working on this now - https://github.com/NebraLtd/hm-diag/tree/%23603-Static-icons-and-assets

**Comment by shawaj** [comment]
Closed by #608 and #615 and #616
