### ISSUE TITLE
Redesign diagnostics page

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#61]
Blocked by #60.

I want to give the diagnostics page a fresh new look.

Here's how it currently looks:
<img width="1679" alt="Screen Shot 2021-06-16 at 9 50 42 AM" src="https://user-images.githubusercontent.com/357664/122188910-590f9680-ce88-11eb-8c03-c679a7739cf9.png">

@vladimirpoleshko can you start mocking up a new design that goes in line with the dashboard design? Doesn't have to have the exact same design but at least have a similar feel to it to make it consistent.

**Comment by shawaj** [comment]
Fixed in #92
