### ISSUE TITLE
Add APN settings configuration for 4G

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#65]
To make it easier to configure 4g, add APN settings configuration

**Comment by vpetersson** [comment]
Some more documentation is available [here](https://www.balena.io/docs/reference/OS/network/2.x/#cellular-modem-setup). I don't think we can write to this path from within the container, but I venture to guess that we can communicate with NetworkManger over DBUS instead.

**Comment by shawaj** [comment]
https://www.balena.io/docs/reference/OS/network/2.x/#cellular-modem-setup

>To set up a cellular connection with your device, just drop the below example configuration into a file in the /resin-boot/system-connections/ directory in the .img or on SD card (if you have it flashed with the OS already) and name it something like cellular. Replace the apn= and number= 

```
[connection]
id=cellular
type=gsm
autoconnect=true

[gsm]
apn=giffgaff.com
number=*99#
password=password
username=giffgaff

[serial]
baud=115200

[ipv4]
method=auto

[ipv6]
addr-gen-mode=stable-privacy
method=auto
```

Also see https://www.balena.io/docs/reference/OS/network/2.x/#changing-the-network-at-runtime

**Comment by shawaj** [comment]
Duplicate of #554
