### ISSUE TITLE
Sync Percentage is incorrect 

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#69]
The sync percentage is showing as 1.0% when it should be 100%.
I have noticed it happen since the testnet 2021.06.24.4.

https://i.imgur.com/dTim208.png

**Comment by vpetersson** [comment]
@ilyastrodubtsev can you jump on this one asap please?

**Comment by shawaj** [comment]
This is the issue I think:

https://github.com/NebraLtd/hm-diag/blob/4aec7e259efbfbe525e666fdf58c130a9a367a57/diagnostics-program/main.py#L301

Blockchain height is being multiplied by 100
