### ISSUE TITLE
Typo at beginning of FileNotFoundError

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#73]
I think the letter f at the beginning of this line is a typo...
https://github.com/NebraLtd/hm-diag/blob/8d4c300237e559e2c1b6e873a4f5b09f78cdfdad/diagnostics-program/main.py#L166

**Comment by ilyastrodubtsev** [comment]
@shawaj These are formatted string literals ", f-strings are string literals with an" f "at the beginning, and curly braces containing expressions that will later be replaced with their values.  The symbol itself is not displayed, it is there to point to the f string, this is not a typo, this is really necessary.
