### ISSUE TITLE
Rework "connected to blockchain" status

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#74]
Helium are updating the "connected" metric in p2p_status to change "connected" to "well-connected" to reflect the fact that in principle 1 connection means it is connected but this check is really meant to determine if it has a good connection.

They will also add a "sessions" count as well.

We need to update the diagnostics to accommodate these changes once they are merged https://github.com/helium/miner/pull/868

**Comment by shawaj** [comment]
Previous output from `miner info p2p_status`

```
/opt/miner # miner info p2p_status
+---------+------+
|  name   |result|
+---------+------+
|connected| yes  |
|dialable | yes  |
|nat_type | none |
| height  |961304|
+---------+------+
```

Current output from latest 

```
/opt/miner # miner info p2p_status
+--------------+------+
|     name     |result|
+--------------+------+
|well-connected| yes  |
|   sessions   |  12  |
|   dialable   | yes  |
|   nat_type   | none |
|    height    |961300|
+--------------+------+
```

This is a breaking change - relates to https://github.com/NebraLtd/helium-miner-software/pull/110#issuecomment-897194758

Error message:
```
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/main.py", line 404, in <module>
 diagnostics      main()
 diagnostics    File "/opt/main.py", line 311, in main
 diagnostics      if int(diagnostics['MH']) > (int(diagnostics['BCH']) - 500):
 diagnostics  ValueError: invalid literal for int() with base 10: 'none'
```

**Comment by shawaj** [comment]
See latest 5 commits in https://github.com/NebraLtd/hm-diag/tree/local-dev-environment for fix

**Comment by robputt** [comment]
This is largely irrelevant since miners no longer sync chain, also soon with SOL move Oracles will use grpc to rust based miner deprecating the old erlang miner.
