### ISSUE TITLE
Multiplying by 100 twice again?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#77]
https://github.com/NebraLtd/hm-diag/blob/992d3ef6ddb8bc7faa4ceaaa402b555d1bfc78f6/diagnostics-program/main.py#L193-L194

I think we are multiplying by 100 twice again here. This was fixed in #69 / #70 but the error seems to have been reintroduced?

**Comment by vpetersson** [comment]
Think this was just in different places. @robputt is tackling rewriting the repo, so let's sort that out.

**Comment by shawaj** [comment]
@vpetersson ah ok cool just wanted to flag it so it doesn't get reproduced going forward

**Comment by vpetersson** [comment]
Yep. We will should have unittests to cover that.

**Comment by robputt** [comment]
Fixed in https://github.com/NebraLtd/hm-diag/pull/81

**Comment by shawaj** [comment]
Closed by #92
