### ISSUE TITLE
Bluetooth no longer working

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#86]
Bluetooth no longer detected on any testnet devices

**Comment by vpetersson** [comment]
Good catch. Deployed an experimental update that we wanted to test there. Wasn't intended to be deployed to mainnet.

**Comment by vpetersson** [comment]
Let's resolve this in https://github.com/NebraLtd/hm-diag/pull/81

**Comment by shawaj** [comment]
I guess the issue is here:

https://github.com/NebraLtd/hm-diag/blob/bebd2b84e8d2e62c7fd459e69238657f8ff38c35/diagnostics-program/utils.py#L87-L107

**Comment by vpetersson** [comment]
I'll let @robputt worry about that :)

**Comment by shawaj** [comment]
Actually it's because the output of:

```
grep 0a12 /sys/bus/usb/devices/*/idVendor
``` 

Is not `0a12` but in fact is `/sys/bus/usb/devices/1-1.3.4/idVendor:0a12`

**Comment by shawaj** [comment]
Fixed in #92
