### ISSUE TITLE
LTE detection no longer working

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#87]
As with #86 the LTE detection is not working correctly

**Comment by vpetersson** [comment]
Same. @robputt is working on a full rewrite so will just wait with these.

**Comment by vpetersson** [comment]
Let's resolve this in https://github.com/NebraLtd/hm-diag/pull/81

**Comment by robputt** [comment]
Can you let me know a device in Balena test net with an LTE module so I may test?

**Comment by shawaj** [comment]
@robputt https://dashboard.balena-cloud.com/devices/204f46e27d5a44bc65fac817ebc77e5b/summary

Winter-wood

**Comment by shawaj** [comment]
related to #88

**Comment by shawaj** [comment]
Fixed in #92
