### ISSUE TITLE
Add versioning for static files

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#91]
In the current iteration, there are two files that are being served from the service:

* `/diagnostics.json`
* `/initFile.txt`

These files are consumed by Hotspot-Production-Tool, and because we need to maintain backward compatibility, we can't break these paths. However, what we should probably do is as follows:

* Create semantic versioning of the API and call the existing version 0.1 (e.g. `/v0.1/diagnostics.json`) and simply alias `/diagnostics.json` to this version.
* Bump up the version and use that for the newer Hotspot-Production-Tool and reformat the JSON payload to something more structured with more readable keys etc.

**Comment by shawaj** [comment]
Not sure this is relevant anymore @kashifpk @KevinWassermann94 - not sure what you think?

**Comment by KevinWassermann94** [comment]
I don't see a need for this

**Comment by shawaj** [comment]
Ok, closing then as we already have the version on settings and the hash of the commit so have enough traceability IMO
