### ISSUE TITLE
Frequency mismatch not handled well

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#94]
As you can see in the below screenshots, this is a 915mhz version of the outdoor and had been asserted in the UK (order mistake) however the diagnostics page says "all ok":

![Screenshot_20210731-040345_Chrome](https://user-images.githubusercontent.com/3359418/128262362-64a7538b-f7a6-4c5a-acd2-0afe3d2343bf.jpg)
![Screenshot_20210731-040459_Chrome](https://user-images.githubusercontent.com/3359418/128262364-9f75cb62-19d3-4a61-a31d-d7bf2c0e0131.jpg)

I guess we should handle this better. At the very least not showing all ok at the top and green on the region and frequency sections.

However, this made me think perhaps we shouldn't let 915s assert with eu868 - not sure if this is possible with the current code from helium though

**Comment by robputt** [comment]
Doesn't appear to be a problem anymore.
