### ISSUE TITLE
Increase test coverage of perform_hw_diagnostics

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-diag#95]
This method is triggering warnings because it has a lot of complexity. It should be broken up into smaller methods that are individually unit tested.

Acceptance criteria:
- Report test coverage before and after work
- Test coverage of perform_hw_diagnostics at least 70%
- Linter warning should go away
- Justify default logic for [value = 1](https://github.com/NebraLtd/hm-diag/pull/92#discussion_r683066937)
- Methods should be consistently named (detect_ecc vs set_diagnostics_bt_lte). All methods that mutate `diagnostics` should have names that indicate that.

**Comment by robputt** [comment]
Test coverage meets > 80% requirement.
