### ISSUE TITLE
Banner linking to the Dashboard

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-diag#97]
To streamline the experience (and to boost visibility for the dashboard), we should add a CTA in the diagnostics page for claiming the device in the dashboard

Follow up: https://github.com/NebraLtd/hm-dashboard/issues/1038

**Acceptance criteria**
- UTM parameters
- Add a top full width banner
- Link to add device page
- Do not store state of whether banner is closed. It may be possible to close the banner between refreshes.

**Comment by shawaj** [comment]
@NebraLtd/developers @NebraLtd/device-team @NebraLtd/tech-support I think this is something we should prioritise to push people to the dashboard.

Perhaps even having "greyed out" features such as restart, reboot, shutdown, and other dashboard specific features that then maybe launches a popup pushing people to sign up for dashboard

**Comment by marvinmarnold** [comment]
@Louisreed can you work on wireframes please?

**Comment by Louisreed** [comment]
![Diagnostics Page - Dashboard notification.png](https://images.zenhubusercontent.com/6240c646b62e3d4770d258f5/13a0fbbc-5f84-44d7-bfae-ecfd4df1bdbd)

**Comment by KevinWassermann94** [comment]
@Louisreed That's looking good! I think we should slightly adjust the detail message though as we don't have any checks if it was claimed. Maybe something like "Use the dashboard now to gain benefits such as remote management, premium firmware and prioritized support"

**Comment by marvinmarnold** [comment]
I'm not sure the horizontal divider is adding much, it seems a little cluttered.

**Comment by Louisreed** [comment]
![Diagnostics Page - Dashboard notification.png](https://images.zenhubusercontent.com/6240c646b62e3d4770d258f5/9a8f51b2-ecf6-45c8-88a3-7b08a5a67e61) @KevinWassermann94 @marvinmarnold Did you want me to propose a design for the feature @shawaj mentioned about showing features greyed out?

**Comment by Louisreed** [comment]
![Diagnostics Page - Dashboard notification - Modal.png](https://images.zenhubusercontent.com/6240c646b62e3d4770d258f5/3ba74f4a-862c-41b7-bc59-beb64b7997ea)

**Comment by marvinmarnold** [comment]
@Louisreed when does the modal appear? I don't think both the modal and banner are necessary.

**Comment by KevinWassermann94** [comment]
@Louisreed I think that adds in too much logic. I think we should only do the banner

**Comment by Louisreed** [comment]
@KevinWassermann94 Sure thing, banner it is!
